2006-02-03  Paolo Carlini  <pcarlini@suse.de>
	* include/tr1/cwchar: New.
	* include/tr1/cwctype: Likewise.
	* include/tr1/wchar.h: Likewise.
	* include/tr1/wctype.h: Likewise.
	* include/Makefile.am: Add.
	* testsuite/tr1/8_c_compatibility/cinttypes/functions: New.
	* testsuite/tr1/8_c_compatibility/cwctype/functions.cc: Likewise.
	* testsuite/tr1/headers.cc: Update.
	* acinclude.m4 ([GLIBCXX_CHECK_C99_TR1]): Add <wchar.h> and
	<wctype.h> checks.
	* docs/html/ext/tr1.html: Update.
	* include/Makefile.in: Regenerate.
	* config.h.in: Likewise.
	* configure: Likewise.

	* testsuite/tr1/8_c_compatibility/cctype/functions.cc: Cosmetic tweak.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@110562 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libstdc++-v3/configure b/libstdc++-v3/configure
--- a/libstdc++-v3/configure
+++ b/libstdc++-v3/configure
@@ -30629,13 +30629,10 @@ main ()
 intmax_t i, numer, denom, base;
 	            const char* s;
 	            char** endptr;
-	            intmax_t ret;
-	            uintmax_t uret;
-	            imaxdiv_t dret;
-	            ret = imaxabs(i);
-	            dret = imaxdiv(numer, denom);
+	            intmax_t ret = imaxabs(i);
+	            imaxdiv_t dret = imaxdiv(numer, denom);
 	            ret = strtoimax(s, endptr, base);
-	            uret = strtoumax(s, endptr, base);
+	            uintmax_t uret = strtoumax(s, endptr, base);
 
   ;
   return 0;
@@ -30678,6 +30675,154 @@ echo "${ECHO_T}$ac_c99_inttypes_tr1" >&6
 
 cat >>confdefs.h <<\_ACEOF
 #define _GLIBCXX_USE_C99_INTTYPES_TR1 1
+_ACEOF
+
+  fi
+
+  # Check for the existence of <wchar.h> functions.
+  echo "$as_me:$LINENO: checking for ISO C99 support to TR1 in <wchar.h>" >&5
+echo $ECHO_N "checking for ISO C99 support to TR1 in <wchar.h>... $ECHO_C" >&6
+  if test "${ac_c99_wchar_tr1+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <wchar.h>
+	          #include <stdio.h>
+	          #include <stdarg.h>
+int
+main ()
+{
+const wchar_t* nptr;
+	          const wchar_t* format;
+	          const wchar_t* s;
+	          wchar_t** endptr;
+	          FILE* stream;
+	          va_list arg;
+	          int base;
+	          float fret = wcstof(nptr, endptr);
+	          long double ldret = wcstold(nptr, endptr);
+	          int ret = vfwscanf(stream, format, arg);
+  	          ret = vswscanf(s, format, arg);
+  	          ret = vwscanf(format, arg);
+	          long long llret = wcstoll(nptr, endptr, base);
+  	          unsigned long long ullret = wcstoull(nptr, endptr, base);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_c99_wchar_tr1=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_c99_wchar_tr1=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  echo "$as_me:$LINENO: result: $ac_c99_wchar_tr1" >&5
+echo "${ECHO_T}$ac_c99_wchar_tr1" >&6
+  if test x"$ac_c99_wchar_tr1" = x"yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define _GLIBCXX_USE_C99_WCHAR_TR1 1
+_ACEOF
+
+  fi
+
+  # Check for the existence of <wctype.h> functions.
+  echo "$as_me:$LINENO: checking for ISO C99 support to TR1 in <wctype.h>" >&5
+echo $ECHO_N "checking for ISO C99 support to TR1 in <wctype.h>... $ECHO_C" >&6
+  if test "${ac_c99_wctype_tr1+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <wctype.h>
+int
+main ()
+{
+wint_t ch;
+	          int ret = iswblank(ch);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_c99_wctype_tr1=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_c99_wctype_tr1=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+  echo "$as_me:$LINENO: result: $ac_c99_wctype_tr1" >&5
+echo "${ECHO_T}$ac_c99_wctype_tr1" >&6
+  if test x"$ac_c99_wctype_tr1" = x"yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define _GLIBCXX_USE_C99_WCTYPE_TR1 1
 _ACEOF
 
   fi
