2000-12-14  Benjamin Kosnik  <bkoz@fillmore.redhat.com>
	* configure.in (CXX): Exit out if mknumeric_limits fails.
	* mknumeric_limits (CXX): Use BUILD_DIR/g++, not g++ in
	path. Consistency with tests_flags.in.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@38262 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libstdc++-v3/configure.in b/libstdc++-v3/configure.in
--- a/libstdc++-v3/configure.in
+++ b/libstdc++-v3/configure.in
@@ -320,7 +320,12 @@ $srcdir/mkc++config $blddir $srcdir
 # Generate bits/std_limits.h and src/limitsMEMBERS.cc
 if test ! -f stamp-limits; then
   $srcdir/mknumeric_limits $blddir $srcdir $xcompiling
-  touch stamp-limits
+  if test ! -f include/bits/std_limits.h; then
+    echo "mknumeric_limits failed to execute properly: exiting"
+    exit 1
+  else
+    touch stamp-limits 
+  fi
 fi
 
 
