* linkage.m4 (GLIBCXX_CHECK_STDLIB_DECL_AND_LINKAGE_0): Define. 	(GLIBCXX_CHECK_STDLIB_SUPPORT): Use it to test for lrand48 	instead of drand48. 	* acconfig.h (HAVE_DRAND48): Renamed to HAVE_LRAND48. 	* crossconfig.m4 (*-freebsd*): Define HAVE_LRAND48 instead of 	HAVE_DRAND48. 	* config.h.in, configure: Regenerate. 	* include/bits/stl_algo.h: Use _GLIBCXX_HAVE_LRAND48 to guard 	lrand48 use.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@71990 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libstdc++-v3/configure b/libstdc++-v3/configure
--- a/libstdc++-v3/configure
+++ b/libstdc++-v3/configure
@@ -26140,7 +26140,72 @@ done
   fi
 
 
-for ac_func in drand48
+  echo "$as_me:$LINENO: checking for lrand48 declaration" >&5
+echo $ECHO_N "checking for lrand48 declaration... $ECHO_C" >&6
+  if test x${glibcxx_cv_func_lrand48_use+set} != xset; then
+    if test "${glibcxx_cv_func_lrand48_use+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+
+      ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+      cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdlib.h>
+int
+main ()
+{
+ lrand48();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  glibcxx_cv_func_lrand48_use=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+glibcxx_cv_func_lrand48_use=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+      ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+
+  fi
+  echo "$as_me:$LINENO: result: $glibcxx_cv_func_lrand48_use" >&5
+echo "${ECHO_T}$glibcxx_cv_func_lrand48_use" >&6
+  if test x$glibcxx_cv_func_lrand48_use = x"yes"; then
+
+for ac_func in lrand48
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -26227,6 +26292,8 @@ _ACEOF
 
 fi
 done
+
+  fi
 
 
   CXXFLAGS="$ac_save_CXXFLAGS"
@@ -46100,7 +46167,72 @@ done
   fi
 
 
-for ac_func in drand48
+  echo "$as_me:$LINENO: checking for lrand48 declaration" >&5
+echo $ECHO_N "checking for lrand48 declaration... $ECHO_C" >&6
+  if test x${glibcxx_cv_func_lrand48_use+set} != xset; then
+    if test "${glibcxx_cv_func_lrand48_use+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+
+      ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+      cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdlib.h>
+int
+main ()
+{
+ lrand48();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  glibcxx_cv_func_lrand48_use=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+glibcxx_cv_func_lrand48_use=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+      ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+
+  fi
+  echo "$as_me:$LINENO: result: $glibcxx_cv_func_lrand48_use" >&5
+echo "${ECHO_T}$glibcxx_cv_func_lrand48_use" >&6
+  if test x$glibcxx_cv_func_lrand48_use = x"yes"; then
+
+for ac_func in lrand48
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -46187,6 +46319,8 @@ _ACEOF
 
 fi
 done
+
+  fi
 
 
   CXXFLAGS="$ac_save_CXXFLAGS"
@@ -48730,7 +48864,7 @@ echo "${ECHO_T}$enable_wchar_t" >&6
 _ACEOF
 
     cat >>confdefs.h <<\_ACEOF
-#define HAVE_DRAND48 1
+#define HAVE_LRAND48 1
 _ACEOF
 
     cat >>confdefs.h <<\_ACEOF
