2008-04-24  Benjamin Kosnik  <bkoz@redhat.com>
	PR libstdc++/35887 
	* configure.ac: Add default argument to GLIBCXX_ENABLE_PARALLEL.
	Move atomic warnings to GLIBCXX_ENABLE_ATOMIC_BUILTINS.
	* acinclude.m4 (GLIBCXX_ENABLE_PARALLEL): Check for --disable-libgomp.
	(GLIBCXX_ENABLE_ATOMIC_BUILTINS): Add warning information.
	* configure: Regenerate.
	* include/Makefile.am (parallel_headers): Make conditional on
	ENABLE_PARALLEL.
	* include/Makefile.in: Regenerate.
	


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@134649 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libstdc++-v3/configure b/libstdc++-v3/configure
--- a/libstdc++-v3/configure
+++ b/libstdc++-v3/configure
@@ -1045,6 +1045,7 @@ Optional Features:
                           [default="-g3 -O0"]
   --enable-libstdcxx-debug
                           build extra debug library [default=no]
+  --enable-libgomp        enable code depending on libgomp [default=yes]
   --enable-cxx-flags=FLAGS
                           pass compiler FLAGS when building library
                           [default=]
@@ -4666,13 +4667,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4669: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4670: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4672: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4673: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4675: output\"" >&5)
+  (eval echo "\"\$as_me:4676: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5716,7 +5717,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5719 "configure"' > conftest.$ac_ext
+  echo '#line 5720 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7178,11 +7179,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7181: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7182: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7185: \$? = $ac_status" >&5
+   echo "$as_me:7186: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7500,11 +7501,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7503: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7504: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7507: \$? = $ac_status" >&5
+   echo "$as_me:7508: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7605,11 +7606,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7608: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7609: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7612: \$? = $ac_status" >&5
+   echo "$as_me:7613: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7660,11 +7661,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7663: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7664: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7667: \$? = $ac_status" >&5
+   echo "$as_me:7668: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10512,7 +10513,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10515 "configure"
+#line 10516 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10612,7 +10613,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10615 "configure"
+#line 10616 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12650,11 +12651,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12654: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12657: \$? = $ac_status" >&5
+   echo "$as_me:12658: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12749,11 +12750,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12752: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12753: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12756: \$? = $ac_status" >&5
+   echo "$as_me:12757: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12801,11 +12802,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12804: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12805: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12808: \$? = $ac_status" >&5
+   echo "$as_me:12809: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13850,7 +13851,7 @@ fi;
     #
     # Fake what AC_TRY_COMPILE does.  XXX Look at redoing this new-style.
     cat > conftest.$ac_ext << EOF
-#line 13853 "configure"
+#line 13854 "configure"
 struct S { ~S(); };
 void bar();
 void foo()
@@ -16906,23 +16907,33 @@ echo "${ECHO_T}$enable_libstdcxx_debug" >&6
 
 
 
-  # NB: libstdc++ may be configured before libgomp: can't check for the actual
-  # dependencies (omp.h and libgomp).
   enable_parallel=no;
-  if test -f $glibcxx_builddir/../libgomp/omp.h; then
-    enable_parallel=yes;
+
+  # Check to see if OpenMP is explicitly disabled.
+  echo "$as_me:$LINENO: checking for libgomp support" >&5
+echo $ECHO_N "checking for libgomp support... $ECHO_C" >&6
+   # Check whether --enable-libgomp or --disable-libgomp was given.
+if test "${enable_libgomp+set}" = set; then
+  enableval="$enable_libgomp"
+
+      case "$enableval" in
+       yes|no) ;;
+       *) { { echo "$as_me:$LINENO: error: Unknown argument to enable/disable libgomp" >&5
+echo "$as_me: error: Unknown argument to enable/disable libgomp" >&2;}
+   { (exit 1); exit 1; }; } ;;
+                          esac
+
+else
+  enable_libgomp=yes
+fi;
+
+  echo "$as_me:$LINENO: result: $enable_libgomp" >&5
+echo "${ECHO_T}$enable_libgomp" >&6
+  if test x$enable_libgomp = xno; then
+    enable_parallel=no
   else
-    { echo "$as_me:$LINENO: $glibcxx_builddir/../libgomp/omp.h not found" >&5
-echo "$as_me: $glibcxx_builddir/../libgomp/omp.h not found" >&6;}
+    enable_parallel=yes
   fi
-
-  # Check to see if it's explicitly disabled.
-#  GLIBCXX_ENABLE(libgomp,,,[enable code depending on libgomp],
-#	[permit yes|no])
-
-#  if test x$enable_libgomp = xno; then
-#    enable_parallel=no
-#  fi
 
   echo "$as_me:$LINENO: checking for parallel mode support" >&5
 echo $ECHO_N "checking for parallel mode support... $ECHO_C" >&6
@@ -18043,8 +18054,6 @@ _ACEOF
   fi
 
 
-# No surprises, no surprises...
-
   echo "$as_me:$LINENO: checking for thread model used by GCC" >&5
 echo $ECHO_N "checking for thread model used by GCC... $ECHO_C" >&6
   target_thread_file=`$CXX -v 2>&1 | sed -n 's/^Thread model: //p'`
@@ -18071,6 +18080,8 @@ _ACEOF
 
 
 
+# Checks for compiler support that don't require linking.
+
 
 
   ac_ext=cc
@@ -18088,7 +18099,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
   # unnecessary for a builtins test.
 
     cat > conftest.$ac_ext << EOF
-#line 18091 "configure"
+#line 18102 "configure"
 int main()
 {
   // NB: _Atomic_word not necessarily int.
@@ -18128,7 +18139,7 @@ echo "${ECHO_T}$enable_atomic_builtinsi" >&6
     rm -f conftest*
 
     cat > conftest.$ac_ext << EOF
-#line 18131 "configure"
+#line 18142 "configure"
 int main()
 {
   typedef bool atomic_type;
@@ -18182,24 +18193,21 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   # If still generic, set to mutex.
   if test $atomicity_dir = "cpu/generic" ; then
     atomicity_dir=cpu/generic/atomicity_mutex
-  fi
-
-
-if test $atomicity_dir = cpu/generic/atomicity_mutex ; then
-  { echo "$as_me:$LINENO: WARNING: No native atomic operations are provided for this platform." >&5
+    { echo "$as_me:$LINENO: WARNING: No native atomic operations are provided for this platform." >&5
 echo "$as_me: WARNING: No native atomic operations are provided for this platform." >&2;}
-  if test $target_thread_file = single; then
-    { echo "$as_me:$LINENO: WARNING: They cannot be faked when thread support is disabled." >&5
+      if test $target_thread_file = single; then
+        { echo "$as_me:$LINENO: WARNING: They cannot be faked when thread support is disabled." >&5
 echo "$as_me: WARNING: They cannot be faked when thread support is disabled." >&2;}
-    { echo "$as_me:$LINENO: WARNING: Thread-safety of certain classes is not guaranteed." >&5
+        { echo "$as_me:$LINENO: WARNING: Thread-safety of certain classes is not guaranteed." >&5
 echo "$as_me: WARNING: Thread-safety of certain classes is not guaranteed." >&2;}
-  else
-    { echo "$as_me:$LINENO: WARNING: They will be faked using a mutex." >&5
+      else
+        { echo "$as_me:$LINENO: WARNING: They will be faked using a mutex." >&5
 echo "$as_me: WARNING: They will be faked using a mutex." >&2;}
-    { echo "$as_me:$LINENO: WARNING: Performance of certain classes will degrade as a result." >&5
+        { echo "$as_me:$LINENO: WARNING: Performance of certain classes will degrade as a result." >&5
 echo "$as_me: WARNING: Performance of certain classes will degrade as a result." >&2;}
+      fi
   fi
-fi
+
 
 
   # All these tests are for C++; save the language and the compiler flags.
@@ -18294,6 +18302,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+# Only do link tests if native. Else, hardcode.
 if $GLIBCXX_IS_NATIVE; then
 
   # We can do more elaborate tests that assume a working linker.
