* gcc_release: Do upload files when local.
From-SVN: r53689

diff --git a/maintainer-scripts/gcc_release b/maintainer-scripts/gcc_release
--- a/maintainer-scripts/gcc_release
+++ b/maintainer-scripts/gcc_release
@@ -349,9 +349,7 @@ upload_files() {
       # Make sure the file will be readable on the server.
       chmod a+r ${x}
       # Copy it.
-      if [ $LOCAL -eq 0 ]; then
-        ${SCP} ${x} ${UPLOAD_PATH} || error "Could not upload ${x}"
-      fi
+      ${SCP} ${x} ${UPLOAD_PATH} || error "Could not upload ${x}"
     fi
   done
 }
