update_web_docs_libstdcxx_svn: No longer ignore all output from the actual copy process.
	* update_web_docs_libstdcxx_svn: No longer ignore all output from
	the actual copy process.
	Check the exit code of the actual copy process; diagnose problems.

From-SVN: r197558

diff --git a/maintainer-scripts/update_web_docs_libstdcxx_svn b/maintainer-scripts/update_web_docs_libstdcxx_svn
--- a/maintainer-scripts/update_web_docs_libstdcxx_svn
+++ b/maintainer-scripts/update_web_docs_libstdcxx_svn
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 
 # "sh update_web_docs_libstdcxx.sh"
@@ -39,7 +39,12 @@ rm -f Makefile
 
 # copy the tree to the onlinedocs area, preserve directory structure
 #find . -depth -print | cpio -pdv $WWWDIR
-find . -depth -print | cpio -pd $WWWDIR > /dev/null 2>&1
+find . -depth -print | cpio -pd $WWWDIR 2>&1 | grep -v "newer or same age version exists"
+
+err=${PIPESTATUS[1]}
+if [ $err -gt 0 ]; then
+    printf "\nCopying failed with error code %d.\n" $err
+fi
 
 cd /
 /bin/rm -rf $WORKDIR
