* Makefile.in: Allow for PWDCMD to override hardcoded pwd. 	* config-ml.in: Likewise. 	* configure: Likewise. 	* configure.in: Likewise.
	boehm-gc:
	* acinclude.m4: Allow for PWDCMD to override hardcoded pwd.
	* aclocal.m4: Regenerate.
	* configure: Regenerate.

	config:
	* acinclude.m4: Allow for PWDCMD to override hardcoded pwd.

	contrib:
	* test_installed: Allow for PWDCMD to override hardcoded pwd.
	* test_summary: Likewise.

	gcc:
	* Makefile.in: Allow for PWDCMD to override hardcoded pwd.
	* configure.in: Likewise.
	* fixinc/check.tpl: Likewise.
	* fixinc/fixinc.dgux: Likewise.
	* fixinc/fixinc.svr4: Likewise.
	* fixinc/fixinc.winnt: Likewise.
	* fixinc/fixincl.sh: Likewise.
	* fixproto: Likewise.
	* configure: Regenerate.

	gcc/ada:
	* Makefile.adalib: Allow for PWDCMD to override hardcoded pwd.
	* Makefile.in: Likewise.

	gcc/f:
	* Make-lang.in: Allow for PWDCMD to override hardcoded pwd.

	gcc/java:
	* Make-lang.in: Allow for PWDCMD to override hardcoded pwd.

	gcc/po:
	* exgettext: Allow for PWDCMD to override hardcoded pwd.

	gcc/treelang:
	* Make-lang.in: Allow for PWDCMD to override hardcoded pwd.

	libf2c:
	* Makefile.in: Allow for PWDCMD to override hardcoded pwd.
	* aclocal.m4: Likewise.
	* configure: Regenerate.

	libjava:
	* acinclude.m4: Allow for PWDCMD to override hardcoded pwd.
	* configure.in: Likewise.
	* aclocal.m4: Regenerate.
	* configure: Regenerate.

	libobjc:
	* aclocal.m4: Allow for PWDCMD to override hardcoded pwd.
	* configure: Regenerate.

	libstdc++-v3:
	* Makefile.am: Allow for PWDCMD to override hardcoded pwd.
	* acinclude.m4: Likewise.
	* docs/html/Makefile: Likewise.
	* aclocal.m4: Regenerate.
	* configure: Regenerate.
	* Makefile.in: Regenerate.

	zlib:
	* configure.in: Allow for PWDCMD to override hardcoded pwd.
	* configure: Regenerate.

	* ChangeLog: Move entries to ChangeLog.gcj.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@53523 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -446,7 +446,7 @@ target_subdir=${target_alias}
 if test ! -d ${target_subdir} ; then
   if mkdir ${target_subdir} ; then true
   else
-    echo "'*** could not make ${PWD=`pwd`}/${target_subdir}" 1>&2
+    echo "'*** could not make ${PWD=`${PWDCMD-pwd}`}/${target_subdir}" 1>&2
     exit 1
   fi
 fi
@@ -457,7 +457,7 @@ if test x"${build_alias}" != x"${host}" ; then
   if test ! -d ${build_subdir} ; then
     if mkdir ${build_subdir} ; then true
     else
-      echo "'*** could not make ${PWD=`pwd`}/${build_subdir}" 1>&2
+      echo "'*** could not make ${PWD=`${PWDCMD-pwd}`}/${build_subdir}" 1>&2
       exit 1
     fi
   fi
