configure (skip-this-dir): Add handling for new shell script...
./ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* configure (skip-this-dir): Add handling for new shell script, which
	might be created by a sub-directory's configure to indicate, this particular
	directory is "unwanted".
	* Makefile.in ($(CONFIGURE_TARGET_MODULES)): Likewise.
./gcc/ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* Makefile.in (CONFIG_LANGUAGES): New macro taking all languages
	which can be configured.
	(LANGUAGES): Use $(CONFIG_LANGUAGES) instead of @all_languages@
	(Makefile): Pass actual LANGUAGES through the environment when
	re-configuring.
	(cstamp-h): Likewise.
	(config.status): Likewise.
	* configure.in (enable_languages): Add new configuration parameter
	"--enable-languages=lang1,lang2,...".
	(${srcdir}/*/config-lang.in): Change handling to configure only
	those directories, that the user might have enabled; default to
	"all" existing languages.
	* configure: Regenerate.
./libchill/ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* configure.in (compiler_name): Add check to detect if this
	language's compiler has been built.
	* configure: Regenerate.
./libf2c/ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* configure.in (compiler_name): Add check to detect if this
	language's compiler has been built.
	* configure: Regenerate.
./libio/ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* configure.in (compiler_name): Add check to detect if this
	language's compiler has been built.
./libobjc/ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* configure.in (compiler_name): Add check to detect if this
	language's compiler has been built.
	* configure: Regenerate.
./libstdc++/ChangeLog:1998-11-26  Manfred Hollstein  <manfred@s-direktnet.de>
	* configure.in (compiler_name): Add check to detect if this
	language's compiler has been built.

From-SVN: r23892

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -677,7 +677,23 @@ fi
 
 ### do common part of configure.in
 
+# If the language specific compiler does not exist, but the "gcc" directory does,
+# we will skip this directory; in this case the sub-directory's common part
+# of configure.in will create a small shell script "skip-this-dir" containing
+# commands to completely clean up any temporary or created files.
+
 . ${tmpfile}.com
+
+if test -f skip-this-dir; then
+	# Perform the same cleanup as the trap handler, minus the "exit 1" of course,
+	# and reset the trap handler.
+	trap 0
+	rm -f Makefile* ${tmpfile}.com ${tmpfile}.tgt ${tmpfile}.hst ${tmpfile}.pos
+	# Execute the final clean-up actions
+	${config_shell} skip-this-dir
+	# and stop configuring this directory.
+	exit 0
+fi
 
 # some sanity checks on configure.in
 case "${srctrigger}" in
