* symlink-tree:  Check number of arguments.
From-SVN: r34900

diff --git a/symlink-tree b/symlink-tree
--- a/symlink-tree
+++ b/symlink-tree
@@ -10,6 +10,11 @@ prog=$0
 srcdir=$1
 ignore="$2"
 
+if test $# -lt 1; then
+  echo "symlink-tree error:  Usage: symlink-tree srcdir \"ignore1 ignore2 ...\""
+  exit 1
+fi
+
 ignore_additional=". .. CVS"
 
 # If we were invoked with a relative path name, adjust ${prog} to work
