PR target/23552 	* acinclude.m4 (LIBGFOR_CHECK_FOR_BROKEN_ISFINITE): New. 	(LIBGFOR_CHECK_FOR_BROKEN_ISNAN): New. 	(LIBGFOR_CHECK_FOR_BROKEN_FPCLASSIFY): New. 	* configure.ac (LIBGFOR_CHECK_FOR_BROKEN_ISFINITE): Add use. 	(LIBGFOR_CHECK_FOR_BROKEN_ISNAN): Add use. 	(LIBGFOR_CHECK_FOR_BROKEN_FPCLASSIFY): Add use. 	* configure: Regenerate. 	* config.h.in: Regenerate. 	* libgfortan.h (isfinite): undef if broken, set if needed. 	(isnan): undef if broken, set if needed.         (fpclassify): undef if broken, set if needed. 	* io/write.c: Remove TODO comment about working isfinite. 	* intrinsics/c99_functions.c (round): Use isfinite instead 	of fpclassify. 	* intrinsics/c99_functions.c (roundf): Ditto.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@104710 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libgfortran/configure b/libgfortran/configure
--- a/libgfortran/configure
+++ b/libgfortran/configure
@@ -19028,7 +19028,7 @@ _ACEOF
 fi
 
 
-# Hack for AIX
+# On AIX, clog is present in libm as __clog
 echo "$as_me:$LINENO: checking for __clog in -lm" >&5
 echo $ECHO_N "checking for __clog in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m___clog+set}" = set; then
@@ -19106,6 +19106,251 @@ _ACEOF
 
 fi
 
+
+# Check for a isfinite macro that works on long doubles.
+
+  echo "$as_me:$LINENO: checking whether isfinite is broken" >&5
+echo $ECHO_N "checking whether isfinite is broken... $ECHO_C" >&6
+if test "${have_broken_isfinite+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  libgfor_check_for_broken_isfinite_save_LIBS=$LIBS
+  LIBS="$LIBS -lm"
+  if test "$cross_compiling" = yes; then
+
+case "${target}" in
+  hppa*-*-hpux*) have_broken_isfinite=yes ;;
+  *) have_broken_isfinite=no ;;
+esac
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_MATH_H
+#include <math.h>
+#endif
+#include <float.h>
+int main ()
+{
+#ifdef isfinite
+#ifdef LDBL_MAX
+  if (!isfinite(LDBL_MAX)) return 1;
+#endif
+#ifdef DBL_MAX
+  if (!isfinite(DBL_MAX)) return 1;
+#endif
+#endif
+return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_broken_isfinite=no
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+have_broken_isfinite=yes
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+  LIBS=$libgfor_check_for_broken_isfinite_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $have_broken_isfinite" >&5
+echo "${ECHO_T}$have_broken_isfinite" >&6
+if test x"$have_broken_isfinite" = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BROKEN_ISFINITE 1
+_ACEOF
+
+fi
+
+# Check for a isnan macro that works on long doubles.
+
+  echo "$as_me:$LINENO: checking whether isnan is broken" >&5
+echo $ECHO_N "checking whether isnan is broken... $ECHO_C" >&6
+if test "${have_broken_isnan+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  libgfor_check_for_broken_isnan_save_LIBS=$LIBS
+  LIBS="$LIBS -lm"
+  if test "$cross_compiling" = yes; then
+
+case "${target}" in
+  hppa*-*-hpux*) have_broken_isnan=yes ;;
+  *) have_broken_isnan=no ;;
+esac
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_MATH_H
+#include <math.h>
+#endif
+#include <float.h>
+int main ()
+{
+#ifdef isnan
+#ifdef LDBL_MAX
+  {
+    long double x;
+    x = __builtin_nanl ("");
+    if (!isnan(x)) return 1;
+    if (isnan(LDBL_MAX)) return 1;
+#ifdef NAN
+    x = (long double) NAN;
+    if (!isnan(x)) return 1;
+#endif
+  }
+#endif
+#ifdef DBL_MAX
+  {
+    double y;
+    y = __builtin_nan ("");
+    if (!isnan(y)) return 1;
+    if (isnan(DBL_MAX)) return 1;
+#ifdef NAN
+    y = (double) NAN;
+    if (!isnan(y)) return 1;
+#endif
+  }
+#endif
+#endif
+return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_broken_isnan=no
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+have_broken_isnan=yes
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+  LIBS=$libgfor_check_for_broken_isnan_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $have_broken_isnan" >&5
+echo "${ECHO_T}$have_broken_isnan" >&6
+if test x"$have_broken_isnan" = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BROKEN_ISNAN 1
+_ACEOF
+
+fi
+
+# Check for a fpclassify macro that works on long doubles.
+
+  echo "$as_me:$LINENO: checking whether fpclassify is broken" >&5
+echo $ECHO_N "checking whether fpclassify is broken... $ECHO_C" >&6
+if test "${have_broken_fpclassify+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  libgfor_check_for_broken_fpclassify_save_LIBS=$LIBS
+  LIBS="$LIBS -lm"
+  if test "$cross_compiling" = yes; then
+
+case "${target}" in
+  hppa*-*-hpux*) have_broken_fpclassify=yes ;;
+  *) have_broken_fpclassify=no ;;
+esac
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_MATH_H
+#include <math.h>
+#endif
+#include <float.h>
+int main ()
+{
+#ifdef fpclassify
+#ifdef LDBL_MAX
+        if (fpclassify(LDBL_MAX) == FP_NAN
+            || fpclassify(LDBL_MAX) == FP_INFINITE) return 1;
+#endif
+#ifdef DBL_MAX
+        if (fpclassify(DBL_MAX) == FP_NAN
+            || fpclassify(DBL_MAX) == FP_INFINITE) return 1;
+#endif
+#endif
+return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_broken_fpclassify=no
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+have_broken_fpclassify=yes
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+  LIBS=$libgfor_check_for_broken_fpclassify_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $have_broken_fpclassify" >&5
+echo "${ECHO_T}$have_broken_fpclassify" >&6
+if test x"$have_broken_fpclassify" = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BROKEN_FPCLASSIFY 1
+_ACEOF
+
+fi
 
 # Fallback in case isfinite is not available.
 echo "$as_me:$LINENO: checking for finite in -lm" >&5
