Merge from trunk revision 252949.
From-SVN: r252952

diff --git a/gotools/Makefile.in b/gotools/Makefile.in
--- a/gotools/Makefile.in
+++ b/gotools/Makefile.in
@@ -160,8 +160,10 @@ ECHO_C = @ECHO_C@
 ECHO_N = @ECHO_N@
 ECHO_T = @ECHO_T@
 EXEEXT = @EXEEXT@
+GCC_FOR_TARGET = @GCC_FOR_TARGET@
 GOC = @GOC@
 GOCFLAGS = $(CFLAGS_FOR_TARGET)
+GOC_FOR_TARGET = @GOC_FOR_TARGET@
 INSTALL = @INSTALL@
 INSTALL_DATA = @INSTALL_DATA@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@
@@ -253,6 +255,7 @@ PWD_COMMAND = $${PWDCMD-pwd}
 STAMP = echo timestamp >
 libgodir = ../$(target_noncanonical)/libgo
 LIBGODEP = $(libgodir)/libgo.la
+LIBGOTOOL = $(libgodir)/libgotool.a
 @NATIVE_FALSE@GOCOMPILER = $(GOC)
 
 # Use the compiler we just built.
@@ -263,36 +266,11 @@ AM_LDFLAGS = -L $(libgodir) -L $(libgodir)/.libs
 GOLINK = $(GOCOMPILER) $(GOCFLAGS) $(AM_GOCFLAGS) $(LDFLAGS) $(AM_LDFLAGS) -o $@
 libgosrcdir = $(srcdir)/../libgo/go
 cmdsrcdir = $(libgosrcdir)/cmd
+libgomiscdir = $(srcdir)/../libgo/misc
 go_cmd_go_files = \
 	$(cmdsrcdir)/go/alldocs.go \
-	$(cmdsrcdir)/go/bug.go \
-	$(cmdsrcdir)/go/build.go \
-	$(cmdsrcdir)/go/clean.go \
-	$(cmdsrcdir)/go/context.go \
-	$(cmdsrcdir)/go/discovery.go \
-	$(cmdsrcdir)/go/doc.go \
-	$(cmdsrcdir)/go/env.go \
-	$(cmdsrcdir)/go/fix.go \
-	$(cmdsrcdir)/go/fmt.go \
-	$(cmdsrcdir)/go/generate.go \
-	$(cmdsrcdir)/go/get.go \
 	$(cmdsrcdir)/go/go11.go \
-	$(cmdsrcdir)/go/help.go \
-	$(cmdsrcdir)/go/http.go \
-	$(cmdsrcdir)/go/list.go \
-	$(cmdsrcdir)/go/main.go \
-	$(cmdsrcdir)/go/note.go \
-	$(cmdsrcdir)/go/pkg.go \
-	$(cmdsrcdir)/go/run.go \
-	$(cmdsrcdir)/go/signal.go \
-	$(cmdsrcdir)/go/signal_unix.go \
-	$(cmdsrcdir)/go/test.go \
-	$(cmdsrcdir)/go/testflag.go \
-	$(cmdsrcdir)/go/tool.go \
-	$(cmdsrcdir)/go/vcs.go \
-	$(cmdsrcdir)/go/version.go \
-	$(cmdsrcdir)/go/vet.go \
-	$(libgodir)/zstdpkglist.go
+	$(cmdsrcdir)/go/main.go
 
 go_cmd_gofmt_files = \
 	$(cmdsrcdir)/gofmt/doc.go \
@@ -313,7 +291,11 @@ go_cmd_cgo_files = \
 GCCGO_INSTALL_NAME := $(shell echo gccgo|sed '$(program_transform_name)')
 GCC_INSTALL_NAME := $(shell echo gcc|sed '$(program_transform_name)')
 GXX_INSTALL_NAME := $(shell echo g++|sed '$(program_transform_name)')
-MOSTLYCLEANFILES = zdefaultcc.go s-zdefaultcc
+MOSTLYCLEANFILES = \
+	zdefaultcc.go s-zdefaultcc \
+	check-gccgo check-gcc gotools.head *-testlog gotools.sum gotools.log \
+	*.sent
+
 
 # For a native build we build the programs using the newly built libgo
 # and install them as regular programs.
@@ -322,19 +304,31 @@ MOSTLYCLEANFILES = zdefaultcc.go s-zdefaultcc
 @NATIVE_TRUE@man_MANS = go.1 gofmt.1
 
 # CHECK_ENV sets up the environment to run the newly built go tool.
+# If you change this, change ECHO_ENV, below.
+# The fl shell variable is used to avoid having FAIL appear
+# in the log unnecessarily.
 @NATIVE_TRUE@CHECK_ENV = \
 @NATIVE_TRUE@	PATH=`echo $(abs_builddir):$${PATH} | sed 's,::*,:,g;s,^:*,,;s,:*$$,,'`; \
 @NATIVE_TRUE@	export PATH; \
 @NATIVE_TRUE@	GCCGO="$(abs_builddir)/check-gccgo"; \
 @NATIVE_TRUE@	export GCCGO; \
+@NATIVE_TRUE@	CC="$(abs_builddir)/check-gcc"; \
+@NATIVE_TRUE@	export CC; \
 @NATIVE_TRUE@	GCCGOTOOLDIR="$(abs_builddir)"; \
 @NATIVE_TRUE@	export GCCGOTOOLDIR; \
 @NATIVE_TRUE@	GO_TESTING_GOTOOLS=yes; \
 @NATIVE_TRUE@	export GO_TESTING_GOTOOLS; \
 @NATIVE_TRUE@	abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
 @NATIVE_TRUE@	LD_LIBRARY_PATH=`echo $${abs_libgodir}/.libs:$${LD_LIBRARY_PATH} | sed 's,::*,:,g;s,^:*,,;s,:*$$,,'`; \
-@NATIVE_TRUE@	export LD_LIBRARY_PATH;
+@NATIVE_TRUE@	export LD_LIBRARY_PATH; \
+@NATIVE_TRUE@	GOROOT=$${abs_libgodir}; \
+@NATIVE_TRUE@	export GOROOT; \
+@NATIVE_TRUE@	fl1="FA"; fl2="IL"; fl="$${fl1}$${fl2}";
 
+
+# ECHO_ENV is a variant of CHECK_ENV to put into a testlog file.
+# It assumes that abs_libgodir is set.
+@NATIVE_TRUE@ECHO_ENV = PATH=`echo $(abs_builddir):$${PATH} | sed 's,::*,:,g;s,^:*,,;s,:*$$,,'` GCCGO='$(abs_builddir)/check-gccgo' CC='$(abs_builddir)/check-gcc' GCCGOTOOLDIR='$(abs_builddir)' GO_TESTING_GOTOOLS=yes LD_LIBRARY_PATH=`echo $${abs_libgodir}/.libs:$${LD_LIBRARY_PATH} | sed 's,::*,:,g;s,^:*,,;s,:*$$,,'` GOROOT=`echo $${abs_libgodir}`
 all: all-am
 
 .SUFFIXES:
@@ -582,8 +576,8 @@ distclean-generic:
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
-@NATIVE_FALSE@uninstall-local:
 @NATIVE_FALSE@install-exec-local:
+@NATIVE_FALSE@uninstall-local:
 clean: clean-am
 
 clean-am: clean-binPROGRAMS clean-generic clean-noinstPROGRAMS \
@@ -682,14 +676,17 @@ zdefaultcc.go: s-zdefaultcc; @true
 s-zdefaultcc: Makefile
 	echo 'package main' > zdefaultcc.go.tmp
 	echo 'const defaultGCCGO = "$(bindir)/$(GCCGO_INSTALL_NAME)"' >> zdefaultcc.go.tmp
-	echo 'const defaultCC = "$(bindir)/$(GCC_INSTALL_NAME)"' >> zdefaultcc.go.tmp
-	echo 'const defaultCXX = "$(bindir)/$(GXX_INSTALL_NAME)"' >> zdefaultcc.go.tmp
+	echo 'const defaultCC = "$(GCC_INSTALL_NAME)"' >> zdefaultcc.go.tmp
+	echo 'const defaultCXX = "$(GXX_INSTALL_NAME)"' >> zdefaultcc.go.tmp
 	echo 'const defaultPkgConfig = "pkg-config"' >> zdefaultcc.go.tmp
 	$(SHELL) $(srcdir)/../move-if-change zdefaultcc.go.tmp zdefaultcc.go
 	$(STAMP) $@ 
 
-@NATIVE_TRUE@go$(EXEEXT): $(go_cmd_go_files) zdefaultcc.go $(LIBGODEP)
-@NATIVE_TRUE@	$(GOLINK) $(go_cmd_go_files) zdefaultcc.go $(LIBS) $(NET_LIBS)
+mostlyclean-local:
+	rm -rf check-go-dir check-runtime-dir cgo-test-dir carchive-test-dir
+
+@NATIVE_TRUE@go$(EXEEXT): $(go_cmd_go_files) $(LIBGOTOOL) $(LIBGODEP)
+@NATIVE_TRUE@	$(GOLINK) $(go_cmd_go_files) $(LIBGOTOOL) $(LIBS) $(NET_LIBS)
 @NATIVE_TRUE@gofmt$(EXEEXT): $(go_cmd_gofmt_files) $(LIBGODEP)
 @NATIVE_TRUE@	$(GOLINK) $(go_cmd_gofmt_files) $(LIBS) $(NET_LIBS)
 @NATIVE_TRUE@cgo$(EXEEXT): $(go_cmd_cgo_files) zdefaultcc.go $(LIBGODEP)
@@ -720,31 +717,96 @@ s-zdefaultcc: Makefile
 # check-gccgo is a little shell script that executes gccgo with the
 # options to pick up the newly built libgo.
 @NATIVE_TRUE@check-gccgo: Makefile
-@NATIVE_TRUE@	rm -f $@
-@NATIVE_TRUE@	echo "#!/bin/sh" > $@
+@NATIVE_TRUE@	rm -f $@ $@.tmp
+@NATIVE_TRUE@	echo "#!/bin/sh" > $@.tmp
 @NATIVE_TRUE@	abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
-@NATIVE_TRUE@	echo "$(GOCOMPILE)" '"$$@"' "-I $${abs_libgodir} -L $${abs_libgodir} -L $${abs_libgodir}/.libs" >> $@
-@NATIVE_TRUE@	chmod +x $@
+@NATIVE_TRUE@	echo "$(GOCOMPILE)" '"$$@"' "-I $${abs_libgodir} -L $${abs_libgodir} -L $${abs_libgodir}/.libs" >> $@.tmp
+@NATIVE_TRUE@	chmod +x $@.tmp
+@NATIVE_TRUE@	mv -f $@.tmp $@
+
+# check-gcc is a little shell script that executes the newly built gcc
+# with the options to pick up the newly built libgo.
+@NATIVE_TRUE@check-gcc: Makefile
+@NATIVE_TRUE@	rm -f $@ $@.tmp
+@NATIVE_TRUE@	echo "#!/bin/sh" > $@.tmp
+@NATIVE_TRUE@	abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
+@NATIVE_TRUE@	echo "$(GCC_FOR_TARGET)" '"$$@"' "-L $${abs_libgodir} -L $${abs_libgodir}/.libs" >> $@.tmp
+@NATIVE_TRUE@	chmod +x $@.tmp
+@NATIVE_TRUE@	mv -f $@.tmp $@
 
 # check-go-tools runs `go test cmd/go` in our environment.
-@NATIVE_TRUE@check-go-tool: go$(EXEEXT) check-head check-gccgo
-@NATIVE_TRUE@	rm -rf check-go-dir
+@NATIVE_TRUE@check-go-tool: go$(EXEEXT) cgo$(EXEEXT) check-head check-gccgo check-gcc
+@NATIVE_TRUE@	rm -rf check-go-dir cmd_go-testlog
 @NATIVE_TRUE@	$(MKDIR_P) check-go-dir/src/cmd/go
 @NATIVE_TRUE@	cp $(cmdsrcdir)/go/*.go check-go-dir/src/cmd/go/
-@NATIVE_TRUE@	cp $(libgodir)/zstdpkglist.go check-go-dir/src/cmd/go/
-@NATIVE_TRUE@	cp zdefaultcc.go check-go-dir/src/cmd/go/
+@NATIVE_TRUE@	cp -r $(cmdsrcdir)/go/internal check-go-dir/src/cmd/go/
+@NATIVE_TRUE@	cp $(libgodir)/zstdpkglist.go check-go-dir/src/cmd/go/internal/load/
+@NATIVE_TRUE@	cp $(libgodir)/zdefaultcc.go check-go-dir/src/cmd/go/internal/cfg/
 @NATIVE_TRUE@	cp -r $(cmdsrcdir)/go/testdata check-go-dir/src/cmd/go/
+@NATIVE_TRUE@	cp -r $(cmdsrcdir)/internal check-go-dir/src/cmd/
+@NATIVE_TRUE@	@abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
+@NATIVE_TRUE@	abs_checkdir=`cd check-go-dir && $(PWD_COMMAND)`; \
+@NATIVE_TRUE@	echo "cd check-go-dir/src/cmd/go && $(ECHO_ENV) GOPATH=$${abs_checkdir} $(abs_builddir)/go$(EXEEXT) test -test.short -test.v" > cmd_go-testlog
 @NATIVE_TRUE@	$(CHECK_ENV) \
 @NATIVE_TRUE@	GOPATH=`cd check-go-dir && $(PWD_COMMAND)`; \
 @NATIVE_TRUE@	export GOPATH; \
-@NATIVE_TRUE@	(cd check-go-dir/src/cmd/go && $(abs_builddir)/go$(EXEEXT) test -test.short -test.v) > cmd_go-testlog 2>&1 || true
+@NATIVE_TRUE@	(cd check-go-dir/src/cmd/go && $(abs_builddir)/go$(EXEEXT) test -test.short -test.v) >> cmd_go-testlog 2>&1 || echo "--- $${fl} go test cmd/go (0.00s)" >> cmd_go-testlog
 @NATIVE_TRUE@	grep '^--- ' cmd_go-testlog | sed -e 's/^--- \(.*\) ([^)]*)$$/\1/'
 
+# check-runtime runs `go test runtime` in our environment.
+# The runtime package is also tested as part of libgo,
+# but the runtime tests use the go tool heavily, so testing
+# here too will catch more problems.
+@NATIVE_TRUE@check-runtime: go$(EXEEXT) cgo$(EXEEXT) check-head check-gccgo check-gcc
+@NATIVE_TRUE@	rm -rf check-runtime-dir runtime-testlog
+@NATIVE_TRUE@	$(MKDIR_P) check-runtime-dir
+@NATIVE_TRUE@	@abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
+@NATIVE_TRUE@	LD_LIBRARY_PATH=`echo $${abs_libgodir}/.libs:$${LD_LIBRARY_PATH} | sed 's,::*,:,g;s,^:*,,;s,:*$$,,'`; \
+@NATIVE_TRUE@	GOARCH=`$(abs_builddir)/go$(EXEEXT) env GOARCH`; \
+@NATIVE_TRUE@	GOOS=`$(abs_builddir)/go$(EXEEXT) env GOOS`; \
+@NATIVE_TRUE@	files=`$(SHELL) $(libgosrcdir)/../match.sh --goarch=$${GOARCH} --goos=$${GOOS} --srcdir=$(libgosrcdir)/runtime --extrafiles="$(libgodir)/runtime_sysinfo.go $(libgodir)/sigtab.go" --tag=libffi`; \
+@NATIVE_TRUE@	echo "$(ECHO_ENV) GC='$(abs_builddir)/check-gccgo -fgo-compiling-runtime' GOARCH=$${GOARCH} GOOS=$${GOOS} $(SHELL) $(libgosrcdir)/../testsuite/gotest --goarch=$${GOARCH} --goos=$${GOOS} --basedir=$(libgosrcdir)/.. --srcdir=$(libgosrcdir)/runtime --pkgpath=runtime --pkgfiles='$${files}' -test.v" > runtime-testlog
+@NATIVE_TRUE@	$(CHECK_ENV) \
+@NATIVE_TRUE@	GC="$${GCCGO} -fgo-compiling-runtime"; \
+@NATIVE_TRUE@	export GC; \
+@NATIVE_TRUE@	GOARCH=`$(abs_builddir)/go$(EXEEXT) env GOARCH`; \
+@NATIVE_TRUE@	GOOS=`$(abs_builddir)/go$(EXEEXT) env GOOS`; \
+@NATIVE_TRUE@	files=`$(SHELL) $(libgosrcdir)/../match.sh --goarch=$${GOARCH} --goos=$${GOOS} --srcdir=$(libgosrcdir)/runtime --extrafiles="$(libgodir)/runtime_sysinfo.go $(libgodir)/sigtab.go" --tag=libffi`; \
+@NATIVE_TRUE@	$(SHELL) $(libgosrcdir)/../testsuite/gotest --goarch=$${GOARCH} --goos=$${GOOS} --basedir=$(libgosrcdir)/.. --srcdir=$(libgosrcdir)/runtime --pkgpath=runtime --pkgfiles="$${files}" -test.v >> runtime-testlog 2>&1 || echo "--- $${fl} go test runtime (0.00s)" >> runtime-testlog
+@NATIVE_TRUE@	grep '^--- ' runtime-testlog | sed -e 's/^--- \(.*\) ([^)]*)$$/\1/'
+
+# check-cgo-test runs `go test misc/cgo/test` in our environment.
+@NATIVE_TRUE@check-cgo-test: go$(EXEEXT) cgo$(EXEEXT) check-head check-gccgo check-gcc
+@NATIVE_TRUE@	rm -rf cgo-test-dir cgo-testlog
+@NATIVE_TRUE@	$(MKDIR_P) cgo-test-dir/misc/cgo
+@NATIVE_TRUE@	cp -r $(libgomiscdir)/cgo/test cgo-test-dir/misc/cgo/
+@NATIVE_TRUE@	@abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
+@NATIVE_TRUE@	echo "cd cgo-test-dir/misc/cgo/test && $(ECHO_ENV) GOTRACEBACK=2 $(abs_builddir)/go$(EXEEXT) test -test.short -test.v" > cgo-testlog
+@NATIVE_TRUE@	$(CHECK_ENV) \
+@NATIVE_TRUE@	GOTRACEBACK=2; \
+@NATIVE_TRUE@	export GOTRACEBACK; \
+@NATIVE_TRUE@	(cd cgo-test-dir/misc/cgo/test && $(abs_builddir)/go$(EXEEXT) test -test.short -test.v) >> cgo-testlog 2>&1 || echo "--- $${fl} go test misc/cgo/test (0.00s)" >> cgo-testlog
+@NATIVE_TRUE@	grep '^--- ' cgo-testlog | sed -e 's/^--- \(.*\) ([^)]*)$$/\1/'
+
+# check-carchive-test runs `go test misc/cgo/testcarchive/carchive_test.go`
+# in our environment.
+@NATIVE_TRUE@check-carchive-test: go$(EXEEXT) cgo$(EXEEXT) check-head check-gccgo check-gcc
+@NATIVE_TRUE@	rm -rf carchive-test-dir carchive-testlog
+@NATIVE_TRUE@	$(MKDIR_P) carchive-test-dir/misc/cgo
+@NATIVE_TRUE@	cp -r $(libgomiscdir)/cgo/testcarchive carchive-test-dir/misc/cgo/
+@NATIVE_TRUE@	@abs_libgodir=`cd $(libgodir) && $(PWD_COMMAND)`; \
+@NATIVE_TRUE@	echo "cd carchive-test-dir/misc/cgo/testcarchive && $(ECHO_ENV) LIBRARY_PATH=`echo $${abs_libgodir}/.libs` $(abs_builddir)/go$(EXEEXT) test -test.v carchive_test.go" > carchive-testlog
+@NATIVE_TRUE@	$(CHECK_ENV) \
+@NATIVE_TRUE@	LIBRARY_PATH=`echo $${abs_libgodir}/.libs:$${LIBRARY_PATH} | sed 's,::*,:,g;s,^:*,,;s,:*$$,,'`; \
+@NATIVE_TRUE@	export LIBRARY_PATH; \
+@NATIVE_TRUE@	(cd carchive-test-dir/misc/cgo/testcarchive && $(abs_builddir)/go$(EXEEXT) test -test.v carchive_test.go) >> carchive-testlog 2>&1 || echo "--- $${fl} go test misc/cgo/testcarchive (0.00s)" >> carchive-testlog
+@NATIVE_TRUE@	grep '^--- ' carchive-testlog | sed -e 's/^--- \(.*\) ([^)]*)$$/\1/'
+
 # The check targets runs the tests and assembles the output files.
-@NATIVE_TRUE@check: check-head check-go-tool
-@NATIVE_TRUE@	mv gotools.head gotools.sum
-@NATIVE_TRUE@	cp gotools.sum gotools.log
-@NATIVE_TRUE@	for file in cmd_go-testlog; do \
+@NATIVE_TRUE@check: check-head check-go-tool check-runtime check-cgo-test check-carchive-test
+@NATIVE_TRUE@	@mv gotools.head gotools.sum
+@NATIVE_TRUE@	@cp gotools.sum gotools.log
+@NATIVE_TRUE@	@for file in cmd_go-testlog runtime-testlog cgo-testlog carchive-testlog; do \
 @NATIVE_TRUE@	  testname=`echo $${file} | sed -e 's/-testlog//' -e 's|_|/|'`; \
 @NATIVE_TRUE@	  echo "Running $${testname}" >> gotools.sum; \
 @NATIVE_TRUE@	  echo "Running $${testname}" >> gotools.log; \
@@ -753,33 +815,30 @@ s-zdefaultcc: Makefile
 @NATIVE_TRUE@	done
 @NATIVE_TRUE@	@echo >> gotools.sum
 @NATIVE_TRUE@	@echo "		=== gotools Summary ===" >> gotools.sum
-@NATIVE_TRUE@	pass=`grep -c '^PASS' gotools.sum`; \
+@NATIVE_TRUE@	@pass=`grep -c '^PASS' gotools.sum`; \
 @NATIVE_TRUE@	if test "$${pass}" -ne "0"; then \
 @NATIVE_TRUE@	  echo "# of expected passes		$${pass}" >> gotools.sum; \
 @NATIVE_TRUE@	fi
-@NATIVE_TRUE@	fail=`grep -c '^FAIL' gotools.sum`; \
+@NATIVE_TRUE@	@fail=`grep -c '^FAIL' gotools.sum`; \
 @NATIVE_TRUE@	if test "$${fail}" -ne "0"; then \
 @NATIVE_TRUE@	  echo "# of unexpected failures	$${fail}" >> gotools.sum; \
 @NATIVE_TRUE@	fi
-@NATIVE_TRUE@	untested=`grep -c '^UNTESTED' gotools.sum`; \
+@NATIVE_TRUE@	@untested=`grep -c '^UNTESTED' gotools.sum`; \
 @NATIVE_TRUE@	if test "$${untested}" -ne "0"; then \
 @NATIVE_TRUE@	  echo "# of untested testcases		$${untested}" >> gotools.sum; \
 @NATIVE_TRUE@	fi
-@NATIVE_TRUE@	echo `echo $(GOC_FOR_TARGET) | sed -e 's/ .*//'`  `$(GOC_FOR_TARGET) -v 2>&1 | grep " version" | sed -n -e 's/.* \(version.*$$\)/\1/p'` >> gotools.sum
-@NATIVE_TRUE@	echo >> gotools.log
-@NATIVE_TRUE@	echo "runtest completed at `date`" >> gotools.log
-@NATIVE_TRUE@	if grep '^FAIL' gotools.sum >/dev/null 2>&1; then exit 1; fi
+@NATIVE_TRUE@	@echo `echo $(GOC_FOR_TARGET) | sed -e 's/ .*//'`  `$(GOC_FOR_TARGET) -v 2>&1 | grep " version" | sed -n -e 's/.* \(version.*$$\)/\1/p'` >> gotools.sum
+@NATIVE_TRUE@	@echo >> gotools.log
+@NATIVE_TRUE@	@echo "runtest completed at `date`" >> gotools.log
+@NATIVE_TRUE@	@if grep '^FAIL' gotools.sum >/dev/null 2>&1; then exit 1; fi
 
-@NATIVE_TRUE@.PHONY: check check-head check-go-tool
+@NATIVE_TRUE@.PHONY: check check-head check-go-tool check-runtime check-cgo-test check-carchive-test
 
 # For a non-native build we have to build the programs using a
 # previously built host (or build -> host) Go compiler.  We should
 # only do this if such a compiler is available.  We also need to get
 # the right values for GOARCH and GOOS in the default build context in
 # the go/build package.  Figure this out later.
-
-mostlyclean-local:
-	rm -rf check-go-dir
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
