config.gcc (sparcv9-*-solaris2): Default to 32-bit code.
        * config.gcc (sparcv9-*-solaris2): Default to 32-bit code.
        (sparc*-*-solaris): Clean up header files.
        * configure.in (AS_SPARC64_FLAG): Error out if can't find it
        and plan on generating 64-bit code.
        * toplev.c (decode_g_option): Remove LINKER_DOES_NOT_WORK_WITH_DWARF2.
        * config/sparc/sol2-64.h: Delete and reuse for default 64-bit code.
        * config/sparc/sol2-sld-64.h: Rename ...
        * config/sparc/sol2-bi.h: ... here.  Remove the bits that checked
        for AS_SPARC64_FLAG not defined.
        * config/sparc/sol2-gld-bi.h: New.
        * config/sparc/sol2-sld.h: Remove.
        * config/sparc/sol26-sld.h: New.
        * config/sparc/sol2.h: Tidy comments.
        * doc/install.texi: Document sparc-solaris configury changes.

From-SVN: r52249

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -7488,8 +7488,8 @@ EOF
 
     fi
 
-    case "$tm_file" in
-    *64*)
+    case "$target" in
+    sparcv9-* | sparc64-*)
 	echo $ac_n "checking for 64 bit support in assembler ($gcc_cv_as)""... $ac_c" 1>&6
 echo "configure:7495: checking for 64 bit support in assembler ($gcc_cv_as)" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_flags64'+set}'`\" = set"; then
@@ -7519,10 +7519,8 @@ fi
 
 echo "$ac_t""$gcc_cv_as_flags64" 1>&6
 	if test "x$gcc_cv_as_flags64" = xno; then
-
-	    tmake_file=`echo " $tmake_file " | sed -e 's, sparc/t-sol2-64 , ,' -e 's,^ ,,' -e 's, $,,'`
-	    dep_tmake_file=`echo " $dep_tmake_file " | sed -e 's, [^ ]*/config/sparc/t-sol2-64 , ,' -e 's,^ ,,' -e 's, $,,'`
-
+	    { echo "configure: error: Assembler does not support 64-bit compilation." 1>&2; exit 1; }
+	    exit 1
 	else
 	    cat >> confdefs.h <<EOF
 #define AS_SPARC64_FLAG "$gcc_cv_as_flags64"
@@ -7536,7 +7534,7 @@ EOF
 
     if test "x$gcc_cv_as_flags64" != xno; then
 	echo $ac_n "checking for assembler offsetable %lo() support""... $ac_c" 1>&6
-echo "configure:7540: checking for assembler offsetable %lo() support" >&5
+echo "configure:7538: checking for assembler offsetable %lo() support" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_offsetable_lo10'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7576,7 +7574,7 @@ EOF
 
   i[34567]86-*-* | x86_64-*-*)
     echo $ac_n "checking assembler instructions""... $ac_c" 1>&6
-echo "configure:7580: checking assembler instructions" >&5
+echo "configure:7578: checking assembler instructions" >&5
     gcc_cv_as_instructions=
     if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x; then
       if test "$gcc_cv_gas_major_version" -eq 2 -a "$gcc_cv_gas_minor_version" -ge 9 -o "$gcc_cv_gas_major_version" -gt 2; then
@@ -7603,7 +7601,7 @@ EOF
     echo "$ac_t""$gcc_cv_as_instructions" 1>&6
 
     echo $ac_n "checking assembler GOTOFF in data directives""... $ac_c" 1>&6
-echo "configure:7607: checking assembler GOTOFF in data directives" >&5
+echo "configure:7605: checking assembler GOTOFF in data directives" >&5
     gcc_cv_as_gotoff_in_data=no
     if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x
     then
@@ -7633,7 +7631,7 @@ EOF
 esac
 
 echo $ac_n "checking assembler dwarf2 debug_line support""... $ac_c" 1>&6
-echo "configure:7637: checking assembler dwarf2 debug_line support" >&5
+echo "configure:7635: checking assembler dwarf2 debug_line support" >&5
 gcc_cv_as_dwarf2_debug_line=no
 # ??? Not all targets support dwarf2 debug_line, even within a version
 # of gas.  Moreover, we need to emit a valid instruction to trigger any
@@ -7689,7 +7687,7 @@ fi
 echo "$ac_t""$gcc_cv_as_dwarf2_debug_line" 1>&6
 
 echo $ac_n "checking assembler --gdwarf2 support""... $ac_c" 1>&6
-echo "configure:7693: checking assembler --gdwarf2 support" >&5
+echo "configure:7691: checking assembler --gdwarf2 support" >&5
 gcc_cv_as_gdwarf2_flag=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x;
 then
@@ -7718,7 +7716,7 @@ fi
 echo "$ac_t""$gcc_cv_as_gdwarf2_flag" 1>&6
 
 echo $ac_n "checking assembler --gstabs support""... $ac_c" 1>&6
-echo "configure:7722: checking assembler --gstabs support" >&5
+echo "configure:7720: checking assembler --gstabs support" >&5
 gcc_cv_as_gstabs_flag=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x;
 then
@@ -7746,7 +7744,7 @@ fi
 echo "$ac_t""$gcc_cv_as_gstabs_flag" 1>&6
 
 echo $ac_n "checking linker PT_GNU_EH_FRAME support""... $ac_c" 1>&6
-echo "configure:7750: checking linker PT_GNU_EH_FRAME support" >&5
+echo "configure:7748: checking linker PT_GNU_EH_FRAME support" >&5
 gcc_cv_ld_eh_frame_hdr=no
 if test x$gcc_cv_gld_major_version != x -a x$gcc_cv_gld_minor_version != x; then
   if test "$gcc_cv_gld_major_version" -eq 2 -a "$gcc_cv_gld_minor_version" -ge 12 -o "$gcc_cv_gld_major_version" -gt 2 && grep 'EMUL = elf' ../ld/Makefile > /dev/null; then
@@ -7909,7 +7907,7 @@ fi
 
 
 echo $ac_n "checking whether to enable maintainer-specific portions of Makefiles""... $ac_c" 1>&6
-echo "configure:7913: checking whether to enable maintainer-specific portions of Makefiles" >&5
+echo "configure:7911: checking whether to enable maintainer-specific portions of Makefiles" >&5
     # Check whether --enable-maintainer-mode or --disable-maintainer-mode was given.
 if test "${enable_maintainer_mode+set}" = set; then
   enableval="$enable_maintainer_mode"
