aarch64: add support for AEABI Build Attributes
GCS (Guarded Control Stack, an Armv9.4-a extension) requires some
caution at runtime. The runtime linker needs to reason about the
compatibility of a set of relocable object files that might not
have been compiled with the same compiler.
Up until now, those metadata, used for the previously mentioned
runtime checks, have been provided to the runtime linker via GNU
properties which are stored in the ELF section ".note.gnu.property".
However, GNU properties are limited in their expressibility, and a
long-term commmitment was taken in the ABI for the Arm architecture
[1] to provide Build Attributes (a.k.a. BAs).

This patch adds the support for emitting AArch64 Build Attributes.
This support includes generating two new assembler directives:
.aeabi_subsection and .aeabi_attribute. These directives are generated
as per the syntax mentioned in spec "Build Attributes for the Arm®
64-bit Architecture (AArch64)" available at [1].

gcc/configure.ac now includes a new check to test whether the
assembler being used to build the toolchain supports these new
directives.
Two behaviors can be observed when -mbranch-protection=[standard|...]
is passed:
- If the assembler support BAs, GCC emits the BAs directives and
no GNU properties.  Note: the static linker will derive the values
of GNU properties from the BAs, and will emit both BAs and GNU
properties into the output object.
- If the assembler do not support them, only .note.gnu.property
section will contain the relevant information.

Bootstrapped on aarch64-none-linux-gnu, and no regression found.

[1]: https://github.com/ARM-software/abi-aa/pull/230

gcc/ChangeLog:

	* config.in: Regenerate.
	* config/aarch64/aarch64-elf-metadata.h
	(class aeabi_subsection): New class for BAs.
	* config/aarch64/aarch64-protos.h
	(aarch64_pacret_enabled): New function.
	* config/aarch64/aarch64.cc
	(HAVE_AS_AEABI_BUILD_ATTRIBUTES): New definition.
	(aarch64_file_end_indicate_exec_stack): Emit BAss.
	(aarch64_pacret_enabled): New function.
	(aarch64_start_file): Indent.
	* configure: Regenerate.
	* configure.ac: New configure check for BAs support in binutils.

gcc/testsuite/ChangeLog:

	* lib/target-supports.exp:
	(check_effective_target_aarch64_gas_has_build_attributes): New checker.
	* gcc.target/aarch64/build-attributes/aarch64-build-attributes.exp: New DejaGNU file.
	* gcc.target/aarch64/build-attributes/build-attribute-bti.c: New test.
	* gcc.target/aarch64/build-attributes/build-attribute-gcs.c: New test.
	* gcc.target/aarch64/build-attributes/build-attribute-pac.c: New test.
	* gcc.target/aarch64/build-attributes/build-attribute-standard.c: New test.
	* gcc.target/aarch64/build-attributes/no-build-attribute-bti.c: New test.
	* gcc.target/aarch64/build-attributes/no-build-attribute-gcs.c: New test.
	* gcc.target/aarch64/build-attributes/no-build-attribute-pac.c: New test.
	* gcc.target/aarch64/build-attributes/no-build-attribute-standard.c: New test.

Co-Authored-By: Srinath Parvathaneni <srinath.parvathaneni@arm.com>

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -28249,6 +28249,43 @@ $as_echo "#define HAVE_AS_SMALL_PIC_RELOCS 1" >>confdefs.h
 
 fi
 
+    # Check if we have binutils support for AEABI build attributes.
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for support of AEABI build attributes" >&5
+$as_echo_n "checking assembler for support of AEABI build attributes... " >&6; }
+if ${gcc_cv_as_aarch64_aeabi_build_attributes+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_aarch64_aeabi_build_attributes=no
+  if test x$gcc_cv_as != x; then
+    $as_echo '
+	.aeabi_subsection aeabi_feature_and_bits, optional, ULEB128
+	.aeabi_attribute Tag_Feature_BTI, 1
+	.aeabi_attribute Tag_Feature_PAC, 1
+	.aeabi_attribute Tag_Feature_GCS, 1
+    ' > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags  -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	gcc_cv_as_aarch64_aeabi_build_attributes=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_aarch64_aeabi_build_attributes" >&5
+$as_echo "$gcc_cv_as_aarch64_aeabi_build_attributes" >&6; }
+if test $gcc_cv_as_aarch64_aeabi_build_attributes = yes; then
+
+$as_echo "#define HAVE_AS_AEABI_BUILD_ATTRIBUTES 1" >>confdefs.h
+
+fi
+
     # Enable Branch Target Identification Mechanism and Return Address
     # Signing by default.
     # Check whether --enable-standard-branch-protection was given.
