configure.in (HAVE_GAS_HIDDEN): Detect sparc binutils 2.12 linker bug.
        * configure.in (HAVE_GAS_HIDDEN): Detect sparc binutils 2.12
        linker bug.

From-SVN: r52752

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -7153,6 +7153,92 @@ elif test x$gcc_cv_as != x; then
 	fi
 	rm -f conftest.s conftest.o conftest.nm1 conftest.nm2
 fi
+
+# Sparc binutils 2.12.0 has broken .hidden support in the linker.
+# I've no idea how to check for this non-native...
+if test x"$gcc_cv_as_hidden" = xyes \
+   && test "$target" = "$host" \
+   && test "$target" = "$build"; then
+  case "$target" in
+    sparc*-*-*)
+	# Compiled from 
+	#	void func1 (void) { }
+	#	void * func2 (void) { return (void *) func1; }
+	#	int main() { return func2() ? 0 : 1; }
+	#	asm(".hidden func1");
+	# but we don't know what the bootstrap compiler is, whether
+	# it can handle asm(), what the option for pic code is.
+	# In addition, the code has been tweaked slightly to run in
+	# both 32 and 64-bit mode.
+	cat > conftest.s <<'EOF'
+	.section ".text"
+	.align 4
+	.global func1
+	.type	 func1,#function
+	.proc	020
+func1:
+	retl
+	nop
+.LLfe1:
+	.size	 func1,.LLfe1-func1
+	.align 4
+.LLGETPC0:
+	retl
+	add %o7,%l7,%l7
+	.align 4
+	.global func2
+	.type	 func2,#function
+	.proc	0120
+func2:
+	save	%sp, -192, %sp
+	sethi	%hi(func1), %o0
+	sethi	%hi(_GLOBAL_OFFSET_TABLE_-4), %l7
+	call	.LLGETPC0
+	add	%l7, %lo(_GLOBAL_OFFSET_TABLE_+4), %l7
+	or	%o0, %lo(func1), %o0
+	ldn	[%l7+%o0], %i0
+	ret
+	restore
+.LLfe2:
+	.size	 func2,.LLfe2-func2
+	.align 4
+	.global main
+	.type	 main,#function
+	.proc	04
+main:
+	!#PROLOGUE# 0
+	save	%sp, -192, %sp
+	call	func2, 0
+	 nop
+	subcc	%g0, %o0, %g0
+	subx	%g0, -1, %i0
+	ret
+	restore
+.LLfe3:
+	.size	 main,.LLfe3-main
+	.hidden func1
+EOF
+	$gcc_cv_as -o conftest.o -KPIC conftest.s
+	$CC -o conftest conftest.o -v 2> conftest-ld1
+	if grep collect2 conftest-ld1 > conftest-ld2; then
+	   :
+	elif grep /usr/ccs/bin/ld conftest-ld1 2> conftest-ld2; then
+	   :
+	else
+	   { echo "configure: error: [internal error -- confused about linking]" 1>&2; exit 1; }
+	   exit 1
+	fi
+	$gcc_cv_ld `sed 's/^ *[^ ]* //' conftest-ld2` > /dev/null 2>&1
+	if (./conftest) >/dev/null 2>&1 ; then
+	   :
+	else
+	   gcc_cv_as_hidden=no
+	fi
+	rm -f conftest*
+	;;
+  esac
+fi
+
 if test x"$gcc_cv_as_hidden" = xyes; then
 	cat >> confdefs.h <<\EOF
 #define HAVE_GAS_HIDDEN 1
@@ -7164,7 +7250,7 @@ libgcc_visibility=$gcc_cv_as_hidden
 
 
 echo $ac_n "checking assembler leb128 support""... $ac_c" 1>&6
-echo "configure:7168: checking assembler leb128 support" >&5
+echo "configure:7254: checking assembler leb128 support" >&5
 gcc_cv_as_leb128=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x; then
   if test "$gcc_cv_gas_major_version" -eq 2 -a "$gcc_cv_gas_minor_version" -ge 11 -o "$gcc_cv_gas_major_version" -gt 2 && grep 'obj_format = elf' ../gas/Makefile > /dev/null; then
@@ -7209,7 +7295,7 @@ fi
 echo "$ac_t""$gcc_cv_as_leb128" 1>&6
 
 echo $ac_n "checking assembler eh_frame optimization""... $ac_c" 1>&6
-echo "configure:7213: checking assembler eh_frame optimization" >&5
+echo "configure:7299: checking assembler eh_frame optimization" >&5
 gcc_cv_as_eh_frame=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x; then
   if test "$gcc_cv_gas_major_version" -eq 2 -a "$gcc_cv_gas_minor_version" -ge 12 -o "$gcc_cv_gas_major_version" -gt 2 && grep 'obj_format = elf' ../gas/Makefile > /dev/null; then
@@ -7290,7 +7376,7 @@ fi
 echo "$ac_t""$gcc_cv_as_eh_frame" 1>&6
 
 echo $ac_n "checking assembler section merging support""... $ac_c" 1>&6
-echo "configure:7294: checking assembler section merging support" >&5
+echo "configure:7380: checking assembler section merging support" >&5
 gcc_cv_as_shf_merge=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x; then
   if test "$gcc_cv_gas_major_version" -eq 2 -a "$gcc_cv_gas_minor_version" -ge 12 -o "$gcc_cv_gas_major_version" -gt 2 && grep 'obj_format = elf' ../gas/Makefile > /dev/null; then
@@ -7316,7 +7402,7 @@ case "$target" in
   # All TARGET_ABI_OSF targets.
   alpha*-*-osf* | alpha*-*-linux* | alpha*-*-*bsd*)
     echo $ac_n "checking assembler supports explicit relocations""... $ac_c" 1>&6
-echo "configure:7320: checking assembler supports explicit relocations" >&5
+echo "configure:7406: checking assembler supports explicit relocations" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_explicit_relocs'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7366,7 +7452,7 @@ EOF
     ;;
   sparc*-*-*)
     echo $ac_n "checking assembler .register pseudo-op support""... $ac_c" 1>&6
-echo "configure:7370: checking assembler .register pseudo-op support" >&5
+echo "configure:7456: checking assembler .register pseudo-op support" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_register_pseudo_op'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7394,7 +7480,7 @@ EOF
     fi
 
     echo $ac_n "checking assembler supports -relax""... $ac_c" 1>&6
-echo "configure:7398: checking assembler supports -relax" >&5
+echo "configure:7484: checking assembler supports -relax" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_relax_opt'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7422,7 +7508,7 @@ EOF
     fi
 
     echo $ac_n "checking assembler and linker support unaligned pc related relocs""... $ac_c" 1>&6
-echo "configure:7426: checking assembler and linker support unaligned pc related relocs" >&5
+echo "configure:7512: checking assembler and linker support unaligned pc related relocs" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_sparc_ua_pcrel'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7449,7 +7535,7 @@ EOF
     fi
 
     echo $ac_n "checking assembler and linker support unaligned pc related relocs against hidden symbols""... $ac_c" 1>&6
-echo "configure:7453: checking assembler and linker support unaligned pc related relocs against hidden symbols" >&5
+echo "configure:7539: checking assembler and linker support unaligned pc related relocs against hidden symbols" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_sparc_ua_pcrel_hidden'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7490,7 +7576,7 @@ EOF
 
     if test "x$gcc_cv_as_flags64" != xno; then
 	echo $ac_n "checking for assembler offsetable %lo() support""... $ac_c" 1>&6
-echo "configure:7494: checking for assembler offsetable %lo() support" >&5
+echo "configure:7580: checking for assembler offsetable %lo() support" >&5
 if eval "test \"`echo '$''{'gcc_cv_as_offsetable_lo10'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -7530,7 +7616,7 @@ EOF
 
   i[34567]86-*-* | x86_64-*-*)
     echo $ac_n "checking assembler instructions""... $ac_c" 1>&6
-echo "configure:7534: checking assembler instructions" >&5
+echo "configure:7620: checking assembler instructions" >&5
     gcc_cv_as_instructions=
     if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x; then
       if test "$gcc_cv_gas_major_version" -eq 2 -a "$gcc_cv_gas_minor_version" -ge 9 -o "$gcc_cv_gas_major_version" -gt 2; then
@@ -7557,7 +7643,7 @@ EOF
     echo "$ac_t""$gcc_cv_as_instructions" 1>&6
 
     echo $ac_n "checking assembler GOTOFF in data directives""... $ac_c" 1>&6
-echo "configure:7561: checking assembler GOTOFF in data directives" >&5
+echo "configure:7647: checking assembler GOTOFF in data directives" >&5
     gcc_cv_as_gotoff_in_data=no
     if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x
     then
@@ -7587,7 +7673,7 @@ EOF
 esac
 
 echo $ac_n "checking assembler dwarf2 debug_line support""... $ac_c" 1>&6
-echo "configure:7591: checking assembler dwarf2 debug_line support" >&5
+echo "configure:7677: checking assembler dwarf2 debug_line support" >&5
 gcc_cv_as_dwarf2_debug_line=no
 # ??? Not all targets support dwarf2 debug_line, even within a version
 # of gas.  Moreover, we need to emit a valid instruction to trigger any
@@ -7643,7 +7729,7 @@ fi
 echo "$ac_t""$gcc_cv_as_dwarf2_debug_line" 1>&6
 
 echo $ac_n "checking assembler --gdwarf2 support""... $ac_c" 1>&6
-echo "configure:7647: checking assembler --gdwarf2 support" >&5
+echo "configure:7733: checking assembler --gdwarf2 support" >&5
 gcc_cv_as_gdwarf2_flag=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x;
 then
@@ -7672,7 +7758,7 @@ fi
 echo "$ac_t""$gcc_cv_as_gdwarf2_flag" 1>&6
 
 echo $ac_n "checking assembler --gstabs support""... $ac_c" 1>&6
-echo "configure:7676: checking assembler --gstabs support" >&5
+echo "configure:7762: checking assembler --gstabs support" >&5
 gcc_cv_as_gstabs_flag=no
 if test x$gcc_cv_gas_major_version != x -a x$gcc_cv_gas_minor_version != x;
 then
@@ -7700,7 +7786,7 @@ fi
 echo "$ac_t""$gcc_cv_as_gstabs_flag" 1>&6
 
 echo $ac_n "checking linker PT_GNU_EH_FRAME support""... $ac_c" 1>&6
-echo "configure:7704: checking linker PT_GNU_EH_FRAME support" >&5
+echo "configure:7790: checking linker PT_GNU_EH_FRAME support" >&5
 gcc_cv_ld_eh_frame_hdr=no
 if test x$gcc_cv_gld_major_version != x -a x$gcc_cv_gld_minor_version != x; then
   if test "$gcc_cv_gld_major_version" -eq 2 -a "$gcc_cv_gld_minor_version" -ge 12 -o "$gcc_cv_gld_major_version" -gt 2 && grep 'EMUL = elf' ../ld/Makefile > /dev/null; then
@@ -7863,7 +7949,7 @@ fi
 
 
 echo $ac_n "checking whether to enable maintainer-specific portions of Makefiles""... $ac_c" 1>&6
-echo "configure:7867: checking whether to enable maintainer-specific portions of Makefiles" >&5
+echo "configure:7953: checking whether to enable maintainer-specific portions of Makefiles" >&5
     # Check whether --enable-maintainer-mode or --disable-maintainer-mode was given.
 if test "${enable_maintainer_mode+set}" = set; then
   enableval="$enable_maintainer_mode"
