configure.in: For --enable-languages=LIST, check for empty LIST.
        * configure.in:  For --enable-languages=LIST, check for empty LIST.
        * configure:  Regenerate.

From-SVN: r34123

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -8958,6 +8958,10 @@ if test x"${enable_languages+set}" != xset; then
 	else
 		enable_languages=all
 	fi
+else
+	if test x"${enable_languages}" = x; then
+		{ echo "configure: error: --enable-languages needs at least one argument" 1>&2; exit 1; }
+	fi
 fi
 subdirs=
 for lang in ${srcdir}/*/config-lang.in ..
