* configure.ac: Add --enable-secureplt. 	(HAVE_AS_REL16): Test for R_PPC_REL16 relocs. 	* config.in: Regenerate. 	* configure: Regenerate. 	* config.gcc (powerpc64-*-linux*, powerpc-*-linux*): Add 	rs6000/secureplt.h to tm_file when enable_secureplt. 	* doc/invoke.texi (msecure-plt, mbss-plt): Document. 	* doc/install.texi: Document --enable-targets and --enable-secureplt. 	Correct xrefs to "Using the GNU Compiler Collection (GCC)". 	* config/rs6000/secureplt.h: New file. 	* config/rs6000/sysv4.h (TARGET_SECURE_PLT): Define. 	(SUBTARGET_OVERRIDE_OPTIONS): Error if -msecure-plt given without 	assembler support. 	(CC1_SECURE_PLT_DEFAULT_SPEC): Define. 	(CC1_SPEC): Delete duplicate mno-sdata.  Invoke cc1_secure_plt_default. 	(SUBTARGET_EXTRA_SPECS): Add cc1_secure_plt_default. 	* config/rs6000/sysv4.opt (msecure-plt, bss-plt): Add options. 	* config/rs6000/rs6000.h (TARGET_SECURE_PLT): Define. 	* config/rs6000/rs6000.c (rs6000_emit_load_toc_table): Handle 	TARGET_SECURE_PLT got register load sequence. 	(rs6000_emit_prologue): Call rs6000_emit_load_toc_table when 	TARGET_SECURE_PLT. 	(rs6000_elf_declare_function_name): Don't emit toc address offset 	word when TARGET_SECURE_PLT. 	* config/rs6000/rs6000.md (elf_high, elf_low): Move past load_toc_*. 	(load_toc_v4_PIC_1) Enable for TARGET_SECURE_PLT. 	(load_toc_v4_PIC_3b, load_toc_v4_PIC_3c): New insns. 	(call, call_value): Mark pic_offset_table_rtx used for sysv pic and 	TARGET_SECURE_PLT. 	(call_nonlocal_sysv, call_value_nonlocal_sysv, sibcall_nonlocal_sysv, 	sibcall_value_nonlocal_sysv): Add 32768 offset when TARGET_SECURE_PLT 	and -fPIC. 	* config/rs6000/tramp.asm (trampoline_initial): Use "bcl 20,31". 	(__trampoline_setup): Likewise.  Init r30 before plt call.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@100415 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -891,6 +891,7 @@ Optional Features:
   --enable-initfini-array	use .init_array/.fini_array sections
   --enable-sjlj-exceptions
                           arrange to use setjmp/longjmp exception handling
+  --enable-secureplt      enable -msecure-plt by default for PowerPC
   --disable-win32-registry
                           disable lookup of installation paths in the
                           Registry on Windows hosts
@@ -7402,7 +7403,7 @@ if test "${gcc_cv_prog_makeinfo_modern+set}" = set; then
 else
     ac_prog_version=`$MAKEINFO --version 2>&1 |
                    sed -n 's/^.*GNU texinfo.* \([0-9][0-9.]*\).*$/\1/p'`
-  echo "configure:7405: version of makeinfo is $ac_prog_version" >&5
+  echo "configure:7406: version of makeinfo is $ac_prog_version" >&5
   case $ac_prog_version in
     '')     gcc_cv_prog_makeinfo_modern=no;;
     4.[2-9]*)
@@ -12361,6 +12362,12 @@ case "$LIBINTL" in *$LIBICONV*)
 	LIBICONV= ;;
 esac
 
+# Check whether --enable-secureplt or --disable-secureplt was given.
+if test "${enable_secureplt+set}" = set; then
+  enableval="$enable_secureplt"
+
+fi;
+
 # Windows32 Registry support for specifying GCC installation paths.
 # Check whether --enable-win32-registry or --disable-win32-registry was given.
 if test "${enable_win32_registry+set}" = set; then
@@ -14729,6 +14736,55 @@ _ACEOF
 
 fi
 
+    case $target in
+      *-*-aix*) conftest_s='	.csect .text[PR]
+LCF..0:
+	addis 11,30,_GLOBAL_OFFSET_TABLE_-LCF..0@ha';;
+      *-*-darwin*)
+	conftest_s='	.text
+LCF0:
+	addis r11,r30,_GLOBAL_OFFSET_TABLE_-LCF0@ha';;
+      *) conftest_s='	.text
+.LCF0:
+	addis 11,30,_GLOBAL_OFFSET_TABLE_-.LCF0@ha';;
+    esac
+
+    echo "$as_me:$LINENO: checking assembler for rel16 relocs" >&5
+echo $ECHO_N "checking assembler for rel16 relocs... $ECHO_C" >&6
+if test "${gcc_cv_as_powerpc_rel16+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_powerpc_rel16=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 17 \) \* 1000 + 0`
+  then gcc_cv_as_powerpc_rel16=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo "$conftest_s" > conftest.s
+    if { ac_try='$gcc_cv_as -a32 -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_powerpc_rel16=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_powerpc_rel16" >&5
+echo "${ECHO_T}$gcc_cv_as_powerpc_rel16" >&6
+if test $gcc_cv_as_powerpc_rel16 = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AS_REL16 1
+_ACEOF
+
+fi
     ;;
 
   mips*-*-*)
