* configure.ac: Check for COMDAT support.  Robustify check for 	SHF_MERGE support. 	* configure: Regenerated. 	* config.in: Likewise. 	* langhooks-def.h (lhd_comdat_group): New function. 	(LANG_HOOKS_COMDAT_GROUP): New macro. 	(LANG_HOOKS_DECLS): Use it. 	* langhooks.c (lhd_comdat_group): Define. 	* langhooks.h (lang_hooks_for_decls): Add comdat_group. 	* output.h (named_section_flags): Make it a macro. 	(named_section_real): New function. 	(default_no_named_section): Add decl parameter. 	(default_elf_asm_named_section): Likewise. 	(default_coff_asm_named_section): Likewise. 	(default_pe_asm_named_section): Likewise. 	* target.h (gcc_target): Adjust type of named_section. 	* varasm.c (named_section_flags): Rename to named_section_real. 	Add decl parameter. 	(default_no_named_section): Add decl parameter. 	(default_elf_asm_named_section): Use COMDAT, if available.  Deal 	with the case that ASM_COMMENT_START is "@". 	(default_coff_asm_named_section): Add decl parameter. 	(default_pe_asm_named_section): Likewise. 	* config/alpha/alpha.c (vms_asm_named_section): Add decl 	parameter. 	(unicosmk_asm_named_section): Likewise. 	* config/arm/arm.c (arm_elf_asm_named_section): Remove. 	* config/arm/elf.h (TARGET_ASM_NAMED_SECTION): Likewise. 	* config/c4x/c4x.c (c4x_asm_named_section): Add decl parameter. 	* config/cris/cris-protos.h (cris_target_asm_named_section): 	Likewise. 	* config/cris/cris.c (cris_target_asm_named_section): 	Likewise. 	* config/h8300/h8300.c (h8300_asm_named_section): Likewise. 	* config/i386/i386-protos.h (i386_pe_asm_named_section): 	Likewise. 	* config/i386/winnt.c (i386_pe_asm_named_section): Likewise. 	* config/m68k/m68k.c (m68k_coff_asm_named_section): Likewise. 	* config/mcore/mcore.c (mcore_asm_named_section): Likewise. 	* config/rs6000/rs6000.c (rs6000_xcoff_asm_named_section): 	Likewise. 	* config/sparc/sparc.c (sparce_elf_asm_named_section): Likewise.
	* cp-objcp-common.h (LANG_HOOKS_COMDAT_GROUP): Define.
	* cp-tree.h (cxx_comdat_group): Declare.
	* decl.c (cxx_comdat_group): New function.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@87557 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -10835,9 +10835,114 @@ fi
 echo "$as_me:$LINENO: result: $gcc_cv_as_shf_merge" >&5
 echo "${ECHO_T}$gcc_cv_as_shf_merge" >&6
 
+if test $gcc_cv_as_shf_merge = no; then
+  echo "$as_me:$LINENO: checking assembler for section merging support" >&5
+echo $ECHO_N "checking assembler for section merging support... $ECHO_C" >&6
+if test "${gcc_cv_as_shf_merge+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_shf_merge=no
+    if test $in_tree_gas = yes; then
+    if test $in_tree_gas_is_elf = yes \
+  && test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 12 \) \* 1000 + 0`
+  then gcc_cv_as_shf_merge=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo '.section .rodata.str, "aMS", %progbits, 1' > conftest.s
+    if { ac_try='$gcc_cv_as --fatal-warnings -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_shf_merge=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_shf_merge" >&5
+echo "${ECHO_T}$gcc_cv_as_shf_merge" >&6
+
+fi
 
 cat >>confdefs.h <<_ACEOF
 #define HAVE_GAS_SHF_MERGE `if test $gcc_cv_as_shf_merge = yes; then echo 1; else echo 0; fi`
+_ACEOF
+
+
+echo "$as_me:$LINENO: checking assembler for COMDAT group support" >&5
+echo $ECHO_N "checking assembler for COMDAT group support... $ECHO_C" >&6
+if test "${gcc_cv_as_comdat_group+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_comdat_group=no
+    if test $in_tree_gas = yes; then
+    if test $in_tree_gas_is_elf = yes \
+  && test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 15 \) \* 1000 + 91`
+  then gcc_cv_as_comdat_group=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo '.section .text,"axG",@progbits,.foo,comdat' > conftest.s
+    if { ac_try='$gcc_cv_as --fatal-warnings -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_comdat_group=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_comdat_group" >&5
+echo "${ECHO_T}$gcc_cv_as_comdat_group" >&6
+
+if test $gcc_cv_as_comdat_group = yes; then
+  gcc_cv_as_comdat_group_percent=no
+else
+ echo "$as_me:$LINENO: checking assembler for COMDAT group support" >&5
+echo $ECHO_N "checking assembler for COMDAT group support... $ECHO_C" >&6
+if test "${gcc_cv_as_comdat_group_percent+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_comdat_group_percent=no
+    if test $in_tree_gas = yes; then
+    if test $in_tree_gas_is_elf = yes \
+  && test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 15 \) \* 1000 + 91`
+  then gcc_cv_as_comdat_group_percent=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo '.section .text,"axG",%progbits,.foo,comdat' > conftest.s
+    if { ac_try='$gcc_cv_as --fatal-warnings -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_comdat_group_percent=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_comdat_group_percent" >&5
+echo "${ECHO_T}$gcc_cv_as_comdat_group_percent" >&6
+
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_GAS_COMDAT_GROUP `if test $gcc_cv_as_comdat_group = yes || test $gcc_cv_as_comdat_group_percent = yes; then echo 1; else echo 0; fi`
 _ACEOF
 
 
