* configure.ac: Add test for dci instruction. 	* configure: Regenerate. 	* config.in: Likewise. 	* config.gcc: Handle --with-cpu=476 and --with-cpu=476fp. 	* doc/invoke.texi: Add cpu_type 476 and 476fp. 	(-mmulhw): Add 476 to description. 	(-mdlmzb): Likewise. 	* config/rs6000/t-fprules (MULTILIB_MATCHES_FLOAT): Include -mcpu=476. 	* config/rs6000/rs6000.c (processor_costs): Add ppc476_cost. 	(processor_target_table): Add 476 and 476fp entries. 	(rs6000_override_options): Use ppc476_cost for PROCESSOR_PPC476. 	(rs6000_issue_rate): Add CPU_PPC476. 	* config/rs6000/rs6000.h (ASM_CPU_476_SPEC): Define. 	(ASM_CPU_SPEC): Pass %(asm_cpu_476) for -mcpu=476 and -mcpu=476fp. 	(processor_type): Add PROCESSOR_PPC476. 	(EXTRA_SPECS): Add asm_cpu_476 string. 	* config/rs6000/rs6000.md: (define_attr "type"): Add isel attribute. 	(define_attr "cpu"): Add ppc476. 	Include 476.md. 	Update comments for 476. 	(isel_signed, isel_unsigned): Change to use "isel" type attribute. 	* config/rs6000/vxworks.h (CPP_SPEC): Handle 464 and 476. 	Update copyright year. 	* config/rs6000/476.md: New file. 	* config/rs6000/40x.md: Add description for "isel" attribute. 	Update copyright year. 	* config/rs6000/440.md: Likewise. 	* config/rs6000/603.md: Likewise. 	* config/rs6000/6xx.md: Likewise. 	* config/rs6000/7450.md: Likewise. 	* config/rs6000/7xx.md: Likewise. 	* config/rs6000/8540.md: Likewise. 	* config/rs6000/cell.md: Likewise. 	* config/rs6000/e300c2c3.md: Likewise. 	* config/rs6000/e500mc.md: Likewise. 	* config/rs6000/mpc.md: Likewise. 	* config/rs6000/power4.md: Likewise. 	* config/rs6000/power5.md: Likewise. 	* config/rs6000/power6.md: Likewise. 	* config/rs6000/power7.md: Likewise. 	* config/rs6000/rios1.md: Likewise. 	* config/rs6000/rios2.md: Likewise. 	* config/rs6000/rs64.md: Likewise.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@152626 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -23515,6 +23515,50 @@ $as_echo "#define HAVE_AS_LWSYNC 1" >>confdefs.h
 
 fi
 
+    case $target in
+      *-*-aix*) conftest_s='	.machine "476"
+	.csect .text[PR]
+	dci 0';;
+      *) conftest_s='	.machine "476"
+	.text
+	dci 0';;
+    esac
+
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for data cache invalidate support" >&5
+$as_echo_n "checking assembler for data cache invalidate support... " >&6; }
+if test "${gcc_cv_as_powerpc_dci+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_powerpc_dci=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 9 \* 1000 \) + 99 \) \* 1000 + 0`
+  then gcc_cv_as_powerpc_dci=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo "$conftest_s" > conftest.s
+    if { ac_try='$gcc_cv_as -a32 -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	gcc_cv_as_powerpc_dci=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_powerpc_dci" >&5
+$as_echo "$gcc_cv_as_powerpc_dci" >&6; }
+if test $gcc_cv_as_powerpc_dci = yes; then
+
+$as_echo "#define HAVE_AS_DCI 1" >>confdefs.h
+
+fi
+
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for .gnu_attribute support" >&5
 $as_echo_n "checking assembler for .gnu_attribute support... " >&6; }
 if test "${gcc_cv_as_powerpc_gnu_attribute+set}" = set; then :
