(stdio.h): Fix return type of fread and fwrite on sysV68.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@10777 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/fixincludes b/gcc/fixincludes
--- a/gcc/fixincludes
+++ b/gcc/fixincludes
@@ -1234,6 +1234,31 @@ EOF
   fi
 fi
 
+# Fix return type of fread and fwrite on sysV68
+file=stdio.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+  chmod a+r ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file, fread and fwrite return type
+  sed -e 's/^\(extern int	fclose(), fflush()\), \(fread(), fwrite()\)\(.*\)$/extern unsigned int	\2;\
+\1\3/' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    rm -f ${LIB}/$file
+  else
+    # Find any include directives that use "file".
+    for include in `egrep '^[       ]*#[    ]*include[      ]*"[^/]' ${LIB}/$file | sed -e 's/^[    ]*#[    ]*include[      ]*"\([^"]*\)".*$/\1/'`; do
+      dir=`echo $file | sed -e s'|/[^/]*$||'`
+      required="$required ${INPUT} $dir/$include ${LIB}/$dir/$include"
+    done
+  fi
+fi
+
 # parameters not const on DECstation Ultrix V4.0 and OSF/1.
 file=stdio.h
 if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
