Tweaks for LynxOS 2.2.2
From-SVN: r8120

diff --git a/gcc/fixincludes b/gcc/fixincludes
--- a/gcc/fixincludes
+++ b/gcc/fixincludes
@@ -1466,7 +1466,7 @@ fi
 
 if [ -r ${LIB}/$file ]; then
   echo Fixing $file
-  sed -e '/#define[ 	][ 	]*void[ 	]int/d' \
+  sed -e '/#[ 	]*define[ 	][ 	]*void[ 	]int/d' \
      ${LIB}/$file > ${LIB}/${file}.sed
   rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
     if cmp $file ${LIB}/$file >/dev/null 2>&1; then
@@ -1744,6 +1744,24 @@ for file in time.h sys/time.h ; do
     fi
   fi
 done
+
+# Fix fcntl prototype in fcntl.h on LynxOS.
+file=fcntl.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+  chmod a+r ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file, fcntl declaration
+  sed -e 's/\(fcntl.*(int, int, \)int)/\1...)/' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    rm -f ${LIB}/$file
+  fi
+fi
 
 if $LINKS; then
   echo 'Making internal symbolic non-directory links'
