Made fixincludes a toplevel build module.
toplevel:
2004-08-31  Paolo Bonzini  <bonzini@gnu.org>

	* Makefile.def (build_modules): Add fixincludes.
	(dependencies): Make gcc depend on fixincludes.
	* configure.in (build_tools): Add fixincludes.
	(build_configdirs): Always include build_libs.
	* Makefile.in: Regenerate.
	* configure: Regenerate.

contrib:
2004-08-04  Paolo Bonzini  <bonzini@gnu.org>

	* gcc_update: Add fixincludes.

fixincludes:
2004-08-31  Paolo Bonzini  <bonzini@gnu.org>

	* .cvsignore: New.
	* Makefile.in: From gcc/fixinc/Makefile.in, making it fully
	autoconfiscated.
	* configure.ac: New.
	* config.h.in: Generate.
	* configure: Generate.
	* aclocal.m4: New.
	* fixlib.h: Remove inclusions of gcc files.
	* system.h: New.

	Other files copied from gcc/fixinc.

gcc:
2004-08-31  Paolo Bonzini  <bonzini@gnu.org>

	* Makefile.in (build_subdir): New substitution.
	(fixinc.sh): Simplify heavily since fixincludes is already built.
	(stmp-fixinc): Depend on specs.ready.
	(install-mkheaders): Use new location of fixincludes.
	(clean): Do not descend into fixinc.
	(FORBUILD): Replace with ../$(build_subdir).
	* configure.ac (build_subdir): Substitute.
	(FORBUILD): Do not set.
	(all_outputs): Remove fixinc/Makefile.
	(default commands): Do not create links in fixinc.
	* mkfixinc.sh: New, from fixinc/mkfixinc.sh without
	the fixincludes configuration steps and substituting
	@FIXINCL@ in fixinc.in.
	* fixinc.in: New, from fixinc/fixincl.sh.

	* fixinc/*: Removed.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@86824 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/fixinc.in b/gcc/fixinc.in
--- a/gcc/fixinc.in
+++ b/gcc/fixinc.in
@@ -28,7 +28,7 @@
 #
 # # # # # # # # # # # # # # # # # # # # #
 
-# Usage: fixincl.sh output-dir input-dir
+# Usage: fixinc.sh output-dir input-dir
 #
 # Directory in which to store the results.
 # Fail if no arg to specify a directory for the output.
@@ -96,13 +96,10 @@ esac
 # Original directory.
 ORIGDIR=`${PWDCMD}`
 export ORIGDIR
-FIXINCL=${ORIGDIR}/fixinc/fixincl
+FIXINCL="@FIXINCL@"
 if [ ! -x $FIXINCL ] ; then
-  FIXINCL=${ORIGDIR}/fixincl
-  if [ ! -x $FIXINCL ] ; then
-    echo "Cannot find working fixincl" >&2
-    exit 1
-  fi
+  echo "Cannot find working fixincl" >&2
+  exit 1
 fi
 export FIXINCL
 
