Fix NeXT <sys/wait.h> problem in <bsd/sys/wait.h> as well, since that is where the file is in NeXTStep 3.0.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@5896 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/fixincludes b/gcc/fixincludes
--- a/gcc/fixincludes
+++ b/gcc/fixincludes
@@ -1018,6 +1018,26 @@ if [ -r ${LIB}/$file ] \
   fi
 fi
 
+# Some versions of NeXTStep apparently have the file fixed above in
+# bsd/sys/wait.h, instead.
+file=bsd/sys/wait.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/bsd 2>/dev/null
+  mkdir ${LIB}/bsd/sys 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ] \
+  && grep 'wait[(]union wait' ${LIB}/$file >/dev/null; then
+  echo Fixing $file, bad wait formal
+  sed -e 's@wait(union wait@wait(void@' ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    rm -f ${LIB}/$file
+  fi
+fi
+
 # Don't use or define the name va_list in stdio.h.
 # This is for ANSI and also to interoperate properly with gvarargs.h.
 file=stdio.h
