*** empty log message ***
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@1018 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/fixincludes b/gcc/fixincludes
--- a/gcc/fixincludes
+++ b/gcc/fixincludes
@@ -467,6 +467,25 @@ if [ -r ${LIB}/$file ]; then
   fi
 fi
 
+# Fix return type of free and {c,m,re}alloc in <malloc.h> on SunOS 4.1.
+file=malloc.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e 's/typedef char \*	malloc_t/typedef void \*	malloc_t/g' \
+  ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
+  fi
+fi
+
+
 # Fix bogus comment in <locale.h> on SunOS 4.1.
 file=locale.h
 if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
