* Makefile.in (compare, compare-lean, compare3): Combined to one         ruleset determining actions to be performed via $@.         (compare4, compare4-lean): New targets.         (gnucompare, gnucompare3): Combined to one ruleset determining         actions to be performed via $@. Also, note which files failed         the comparison test in .bad_compare.         (gnucompare-lean, gnucompare3-lean, gnucompare4-lean): New targets.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@16184 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/Makefile.in b/gcc/Makefile.in
--- a/gcc/Makefile.in
+++ b/gcc/Makefile.in
@@ -2617,18 +2617,20 @@ bootstrap3: force
 # stage2 directory.
 
 # ./ avoids bug in some versions of tail.
-compare: force
+compare compare3 compare4 compare-lean compare3-lean compare4-lean: force
 	-rm -f .bad_compare
+	case "$@" in compare | compare-lean ) stage=2 ;; * ) stage=`echo $@ | sed -e 's,^compare\([0-9][0-9]*\).*,\1,'` ;; esac; \
 	for file in *$(objext); do \
 	  tail +16c ./$$file > tmp-foo1; \
-	  tail +16c stage2/$$file > tmp-foo2 \
+	  tail +16c stage$$stage/$$file > tmp-foo2 \
 	    && (cmp tmp-foo1 tmp-foo2 > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
 	done
+	case "$@" in compare | compare-lean ) stage=2 ;; * ) stage=`echo $@ | sed -e 's,^compare\([0-9][0-9]*\).*,\1,'` ;; esac; \
 	for dir in tmp-foo $(SUBDIRS); do \
 	  if [ "`echo $$dir/*$(objext)`" != "$$dir/*$(objext)" ] ; then \
 	    for file in $$dir/*$(objext); do \
 	      tail +16c ./$$file > tmp-foo1; \
-	      tail +16c stage2/$$file > tmp-foo2 \
+	      tail +16c stage$$stage/$$file > tmp-foo2 \
 	        && (cmp tmp-foo1 tmp-foo2 > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
 	    done; \
 	  fi; \
@@ -2638,80 +2640,39 @@ compare: force
 	  echo "Bootstrap comparison failure!"; \
 	  cat .bad_compare; \
 	  exit 1; \
-	else true; \
+	else \
+	  case "$@" in \
+	    *-lean ) rm -rf stage$$stage ;; \
+	  esac; true; \
 	fi
-
-# ./ avoids bug in some versions of tail.
-compare-lean: force
-	-rm -f .bad_compare
-	for file in *$(objext); do \
-	  tail +16c ./$$file > tmp-foo1; \
-	  tail +16c stage2/$$file > tmp-foo2 \
-	    && (cmp tmp-foo1 tmp-foo2 > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
-	done
-	for dir in tmp-foo $(SUBDIRS); do \
-	  if [ "`echo $$dir/*$(objext)`" != "$$dir/*$(objext)" ] ; then \
-	    for file in $$dir/*$(objext); do \
-	      tail +16c ./$$file > tmp-foo1; \
-	      tail +16c stage2/$$file > tmp-foo2 \
-	        && (cmp tmp-foo1 tmp-foo2 > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
-	    done; \
-	  fi; \
-	done
-	-rm -f tmp-foo*
-	if [ -f .bad_compare ]; then \
-	  echo "Bootstrap comparison failure!"; \
-	  cat .bad_compare; \
-	  exit 1; \
-	else rm -rf stage2; \
-	fi
-
-# Similar, but compare with stage3 directory
-compare3: force
-	for file in *$(objext); do \
-	  tail +16c ./$$file > tmp-foo1; \
-	  tail +16c stage3/$$file > tmp-foo2 2>/dev/null \
-	    && (cmp tmp-foo1 tmp-foo2 || echo $$file differs) || true; \
-	done
-	for dir in tmp-foo $(SUBDIRS); do \
-	  if [ "`echo $$dir/*$(objext)`" != "$$dir/*$(objext)" ] ; then \
-	    for file in $$dir/*$(objext); do \
-	      tail +16c ./$$file > tmp-foo1; \
-	      tail +16c stage3/$$file > tmp-foo2 2>/dev/null \
-	        && (cmp tmp-foo1 tmp-foo2 || echo $$file differs) || true; \
-	    done; \
-	  fi; \
-	done
-	-rm -f tmp-foo*
 
 # Compare the object files in the current directory with those in the
 # stage2 directory.  Use gnu cmp (diffutils v2.4 or later) to avoid
 # running tail and the overhead of twice copying each object file.
 
-gnucompare: force
+gnucompare gnucompare3 gnucompare4 gnucompare-lean gnucompare3-lean gnucompare4-lean: force
+	-rm -f .bad_compare
+	case "$@" in gnucompare | gnucompare-lean ) stage=2 ;; * ) stage=`echo $@ | sed -e 's,^gnucompare\([0-9][0-9]*\).*,\1,'` ;; esac; \
 	for file in *$(objext); do \
-	  cmp --ignore-initial=16 $$file stage2/$$file || true ; \
+	  (cmp --ignore-initial=16 $$file stage$$stage/$$file > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
 	done
+	case "$@" in gnucompare | gnucompare-lean ) stage=2 ;; * ) stage=`echo $@ | sed -e 's,^gnucompare\([0-9][0-9]*\).*,\1,'` ;; esac; \
 	for dir in tmp-foo $(SUBDIRS); do \
 	  if [ "`echo $$dir/*$(objext)`" != "$$dir/*$(objext)" ] ; then \
 	    for file in $$dir/*$(objext); do \
-	      cmp --ignore-initial=16 $$file stage2/$$file || true ; \
+	      (cmp --ignore-initial=16 $$file stage$$stage/$$file > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
 	    done; \
 	  fi; \
 	done
-
-# Similar, but compare with stage3 directory
-gnucompare3: force
-	for file in *$(objext); do \
-	  cmp --ignore-initial=16 $$file stage3/$$file || true ; \
-	done
-	for dir in tmp-foo $(SUBDIRS); do \
-	  if [ "`echo $$dir/*$(objext)`" != "$$dir/*$(objext)" ] ; then \
-	    for file in $$dir/*$(objext); do \
-	      cmp --ignore-initial=16 $$file stage3/$$file || true ; \
-	    done; \
-	  fi; \
-	done
+	if [ -f .bad_compare ]; then \
+	  echo "Bootstrap comparison failure!"; \
+	  cat .bad_compare; \
+	  exit 1; \
+	else \
+	  case "$@" in \
+	    *-lean ) rm -rf stage$$stage ;; \
+	  esac; true; \
+	fi
 
 # Copy the object files from a particular stage into a subdirectory.
 stage1-start:
