Makefile (compare): Exit with nonzero status if there are comparison failures.
        * Makefile (compare): Exit with nonzero status if there
        are comparison failures.  Note which files failed the
        comparison test in .bad_compare.
For toplevel "make bootstrap".

From-SVN: r15400

diff --git a/gcc/Makefile.in b/gcc/Makefile.in
--- a/gcc/Makefile.in
+++ b/gcc/Makefile.in
@@ -2589,21 +2589,30 @@ bootstrap3: force
 
 # ./ avoids bug in some versions of tail.
 compare: force
+	-rm -f .bad_compare
 	for file in *$(objext); do \
 	  tail +16c ./$$file > tmp-foo1; \
-	  tail +16c stage2/$$file > tmp-foo2 2>/dev/null \
-	    && (cmp tmp-foo1 tmp-foo2 || echo $$file differs) || true; \
+	  tail +16c stage2/$$file > tmp-foo2 \
+	    && (cmp tmp-foo1 tmp-foo2 > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
 	done
 	for dir in tmp-foo $(SUBDIRS); do \
 	  if [ "`echo $$dir/*$(objext)`" != "$$dir/*$(objext)" ] ; then \
 	    for file in $$dir/*$(objext); do \
 	      tail +16c ./$$file > tmp-foo1; \
-	      tail +16c stage2/$$file > tmp-foo2 2>/dev/null \
-	        && (cmp tmp-foo1 tmp-foo2 || echo $$file differs) || true; \
+	      tail +16c stage2/$$file > tmp-foo2 \
+	        && (cmp tmp-foo1 tmp-foo2 > /dev/null 2>&1 || echo $$file differs >> .bad_compare) || true; \
 	    done; \
 	  fi; \
 	done
 	-rm -f tmp-foo*
+	if [ -f .bad_compare ]; then \
+	  echo "Bootstrap comparison failure!"; \
+	  cat .bad_compare; \
+	  exit 1; \
+	else true; \
+	fi
+	
+	
 
 # Similar, but compare with stage3 directory
 compare3: force
