2004-08-20  Michael Koch  <konqueror@gmx.de>
	* configure.in: Renamed to configure.ac.
	* configure.ac: New file.
	* configure, Makefile.in, gcj/Makefile.in, include/Makefile.in
	include/config.h.in, testsuite/Makefile.in: Regenerated.


git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@86326 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libjava/configure b/libjava/configure
--- a/libjava/configure
+++ b/libjava/configure
@@ -13289,8 +13289,8 @@ if test ! -f gnu/classpath/Configuration.java; then
   # but we add /dev/null to the input list so that grep will print the
   # filename of Configuration.java in case it finds any matches.
   if grep @ gnu/classpath/Configuration.java /dev/null; then
-    { { echo "$as_me:$LINENO: error: configure.in is missing the substitutions above" >&5
-echo "$as_me: error: configure.in is missing the substitutions above" >&2;}
+    { { echo "$as_me:$LINENO: error: configure.ac is missing the substitutions above" >&5
+echo "$as_me: error: configure.ac is missing the substitutions above" >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
