PR libgcj/30606: 	* configure, include/config.h.in: Rebuilt. 	* configure.ac: Check for magic_t in magic.h. 	* java/net/natVMURLConnection.cc: Use HAVE_MAGIC_T.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/trunk@121425 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/libjava/configure b/libjava/configure
--- a/libjava/configure
+++ b/libjava/configure
@@ -15768,6 +15768,75 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for magic_t" >&5
+echo $ECHO_N "checking for magic_t... $ECHO_C" >&6
+if test "${ac_cv_type_magic_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_MAGIC_H
+#include <magic.h>
+#endif
+
+int
+main ()
+{
+if ((magic_t *) 0)
+  return 0;
+if (sizeof (magic_t))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_magic_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_magic_t=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_magic_t" >&5
+echo "${ECHO_T}$ac_cv_type_magic_t" >&6
+if test $ac_cv_type_magic_t = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MAGIC_T 1
+_ACEOF
+
+fi
+
 
 echo "$as_me:$LINENO: checking for in_addr_t" >&5
 echo $ECHO_N "checking for in_addr_t... $ECHO_C" >&6
