testsuite: fix gotest for absolute srcdir
    The recent changes to Makefile.am mean that if you configure with an
    absolute path as srcdir then gotest will be invoked with absolute paths
    for the files.  That case never worked.  This patch fixes it.
    
    Reviewed-on: https://go-review.googlesource.com/25587

From-SVN: r239256

diff --git a/libgo/testsuite/gotest b/libgo/testsuite/gotest
--- a/libgo/testsuite/gotest
+++ b/libgo/testsuite/gotest
@@ -217,18 +217,27 @@ x)
 		;;
 	*)
 		for f in $pkgfiles; do
-		    if test -f $basedir/$f; then
-			b=`basename $f`
-			rm -f $b
-			cp $basedir/$f $b
-		    elif test -f ../../$f; then
-			b=`basename $f`
-			rm -f $b
-			cp ../../$f $b
-		    else
-			echo "file $f not found" 1>&2
-			exit 1
-		    fi
+                    case $f in
+                    /*)
+                        b=`basename $f`
+                        rm -f $b
+                        cp $f $b
+                        ;;
+                    *)
+		        if test -f $basedir/$f; then
+			  b=`basename $f`
+			  rm -f $b
+			  cp $basedir/$f $b
+		        elif test -f ../../$f; then
+			  b=`basename $f`
+			  rm -f $b
+			  cp ../../$f $b
+		        else
+			  echo "file $f not found" 1>&2
+			  exit 1
+		        fi
+                        ;;
+                    esac
 		done
 		for f in `cd $srcdir; ls *_test.go`; do
 		    rm -f $f
@@ -252,18 +261,27 @@ x)
 		;;
 	*)
 		for f in $pkgfiles; do
-		    if test -f $basedir/$f; then
-			b=`basename $f`
-			rm -f $b
-			cp $basedir/$f $b
-		    elif test -f ../../$f; then
-			b=`basename $f`
-			rm -f $b
-			cp ../../$f $b
-		    else
-			echo "file $f not found" 1>&2
-			exit 1
-		    fi
+                    case $f in
+                    /*)
+                        b=`basename $f`
+                        rm -f $b
+                        cp $f $b
+                        ;;
+                    *)
+		        if test -f $basedir/$f; then
+			  b=`basename $f`
+			  rm -f $b
+			  cp $basedir/$f $b
+		        elif test -f ../../$f; then
+			  b=`basename $f`
+			  rm -f $b
+			  cp ../../$f $b
+		        else
+			  echo "file $f not found" 1>&2
+			  exit 1
+		        fi
+                        ;;
+                    esac
 		done
 		;;
 	esac
