gccrs: disable macos github workflow
Its broken at the moment.

ChangeLog:

	* .github/workflows/ccpp.yml: comment it out

Signed-off-by: Philip Herron <herron.philip@googlemail.com>

diff --git a/.github/workflows/ccpp.yml b/.github/workflows/ccpp.yml
--- a/.github/workflows/ccpp.yml
+++ b/.github/workflows/ccpp.yml
@@ -367,64 +367,64 @@ jobs:
               exit 0; \
             fi
 
-  build-and-check-clang-macos:
+  # build-and-check-clang-macos:
 
-    env:
-      # Force CC/CXX to be explicitly clang to make it clear which compiler is used
-      CC: clang
-      CXX: clang++
+  #   env:
+  #     # Force CC/CXX to be explicitly clang to make it clear which compiler is used
+  #     CC: clang
+  #     CXX: clang++
 
-    runs-on: macos-13
+  #   runs-on: macos-13
 
-    steps:
-    - uses: actions/checkout@v4
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Install Deps
-      run: |
-          brew install dejagnu mpfr libmpc gmp;
-          # install Rust directly using rustup
-          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=1.72.0;
+  #   - name: Install Deps
+  #     run: |
+  #         brew install dejagnu mpfr libmpc gmp;
+  #         # install Rust directly using rustup
+  #         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=1.72.0;
 
-    - name: Make Source Read-Only
-      run: chmod -R a-w ./*
+  #   - name: Make Source Read-Only
+  #     run: chmod -R a-w ./*
 
-    - name: Configure
-      run: |
-           mkdir -p gccrs-build;
-           cd gccrs-build;
-           ../configure \
-               --enable-languages=rust \
-               --disable-bootstrap \
-               --enable-multilib \
-               --with-native-system-header-dir=/usr/include \
-               --with-sysroot=$(xcrun --show-sdk-path)
+  #   - name: Configure
+  #     run: |
+  #          mkdir -p gccrs-build;
+  #          cd gccrs-build;
+  #          ../configure \
+  #              --enable-languages=rust \
+  #              --disable-bootstrap \
+  #              --enable-multilib \
+  #              --with-native-system-header-dir=/usr/include \
+  #              --with-sysroot=$(xcrun --show-sdk-path)
 
-    - name: Build
-      shell: bash
-      run: |
-           cd gccrs-build; \
-           make -j $(sysctl -n hw.ncpu) 2>&1 | tee log
+  #   - name: Build
+  #     shell: bash
+  #     run: |
+  #          cd gccrs-build; \
+  #          make -j $(sysctl -n hw.ncpu) 2>&1 | tee log
 
-    - name: Run Tests
-      run: |
-           cd gccrs-build; \
-           make check-rust
-    - name: Archive check-rust results
-      uses: actions/upload-artifact@v3
-      with:
-        name: check-rust-logs-macos
-        path: |
-          gccrs-build/gcc/testsuite/rust/
-    - name: Check regressions
-      run: |
-           cd gccrs-build; \
-           if grep -e "unexpected" -e "unresolved" -e "ERROR:" gcc/testsuite/rust/rust.sum;\
-           then \
-              echo "::error title=Regression test failed::some tests are not correct"; \
-              exit 1; \
-            else \
-              exit 0; \
-            fi
+  #   - name: Run Tests
+  #     run: |
+  #          cd gccrs-build; \
+  #          make check-rust
+  #   - name: Archive check-rust results
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: check-rust-logs-macos
+  #       path: |
+  #         gccrs-build/gcc/testsuite/rust/
+  #   - name: Check regressions
+  #     run: |
+  #          cd gccrs-build; \
+  #          if grep -e "unexpected" -e "unresolved" -e "ERROR:" gcc/testsuite/rust/rust.sum;\
+  #          then \
+  #             echo "::error title=Regression test failed::some tests are not correct"; \
+  #             exit 1; \
+  #           else \
+  #             exit 0; \
+  #           fi
 
   build-and-check-asan:
 
