ci: check Signed-off-by lines (and others) are at the end
Check Signed-off-by/Reviewed-by/Co-authored-by lines are all grouped and
last in commit log.

ChangeLog:

	* .github/workflows/commit-format.yml: Check SoB lines are last.

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

diff --git a/.github/workflows/commit-format.yml b/.github/workflows/commit-format.yml
--- a/.github/workflows/commit-format.yml
+++ b/.github/workflows/commit-format.yml
@@ -91,6 +91,22 @@ jobs:
             fi
           done;
 
-          exit $retval;
+          ## check no Signed-off-by in the middle.
+          while read -r f; do
+            echo -n "$f : "
+               if awk 'BEGIN { in_footer = 0; error = 0;}
+                       { DEFAULT = 1; }
+                       /^Signed-off-by/ { in_footer = 1; DEFAULT = 0;}
+                       /^Co-authored-by/ { in_footer = 1; DEFAULT = 0;}
+                       /^Reviewed-by/  { in_footer = 1; DEFAULT = 0;}
+                       /^\s*$/  { DEFAULT = 0; }
+                       DEFAULT { if (in_footer == 1) { printf $0 " appears after some Signed-off-by/Co-authored-by line "; error = 1; exit (1);} }';
+               then
+                   echo OK
+               else
+                   echo KO
+                   retval=1
+               fi < <(git log "$f" -1 --format="%B")
+          done < <(git rev-list --reverse "$rev_list" )
 
-  
+          exit $retval;
